01org/cc-oci-runtime

- INSTALL_DOCKER.rst
General updates to the INSTALL_DOCKER.rst file.
Some better practices, syntactical cleanups and more information.
> Install docker updates

- src/networking.c
- src/networking.h
- src/oci.h
- src/process.c
- Fixed memory leak in network interface discovery
- Check IP and Subnet address validity
- Misc formatting changes
> Networking: Incorporate code review feedback

- .travis.yml
Empty for now until we figure out how to solve our dependencies
with a 12.04 LTS Ubuntu image.
> travis: NOOP travis support

- src/hypervisor.c
This is a workaround for using stdio as console device for qemu.
This solution bypasses the shim pipes and writes to docker named
pipes. We should resort to using stdio as console once that is resolved.
> Fix for non-interactive docker output and docker attach

- src/hypervisor.c
- src/networking.c
- src/networking.h
- src/process.c
- Add support for default gateway configuration
- Remove the hardcoding of the network interface and use the first valid IPv4 interface
- Incorporate some code review feedback
> Networking - Default Gateway Support

- README.rst
> Add a Travis build status badge to the README.

- Makefile.am
- README.rst
- data/cc-oci-runtime.sh.in
- src/main.c
> Disable global log

- .travis-setup.sh
- .travis.yml
- Makefile.am
- autogen.sh
- configure.ac
- versions.txt
I looked a bit at travis, here's the first resulting series: various small cleanups and shaves 30s-ish of the build.
> Travis setup improvements

- .travis.yml
Add an encrypted COVERITY_SCAN_NOTIFICATION_EMAIL address for Coverity
Scan notifications.
> CI: Add Coverity notification email.

- .gitignore
That generated file was added recently, but wasn't part of the
.gitignore file just yet.
> gitignore: Ignore cc-oci-runtime.sh

- src/logging.c
The title should be more descriptive.. IMHO
> Resource leak fix and some code cleanup

- src/commands/create.c
> output: Remove the spurious 'container created' message

- src/process.c
Move the network configuration and the discovery process to
the child. The parent runs the hooks and on completion of the hooks
notifies the child of the hook execution status. The child will launch
the VM if the hooks were executed successfully, or will exit.
This reduces the complexity and the latency in the network setup.
> Networking: Move network discovery and configuration to child

- src/mount.c
Fixes #23 
docker -v allows to mount regular files, but cc-oci-runtime assumes that a mount will be a directory.
This patch verify if a mount is done using a regular file. If true it creates a file in the destination target with the same permissions than the original file, this new file is used as mount destination file.
> mount: fix mount when using regular files

- tests/functional/common.bash.in
- tests/functional/help.bats
- tests/functional/kill.bats
- tests/functional/pause.bats
- tests/functional/start.bats
- tests/functional/state.bats
- tests/functional/version.bats
All files should contain the standard header, where possible.
> Tests: Add standard header to bats tests.

- tests/integration/docker/commit.bats
- tests/integration/docker/create.bats
- tests/integration/docker/export.bats
- tests/integration/docker/info.bats
- tests/integration/docker/inspect.bats
- tests/integration/docker/kill.bats
- tests/integration/docker/load.bats
- tests/integration/docker/logs.bats
- tests/integration/docker/network.bats
- tests/integration/docker/port.bats
- tests/integration/docker/restart.bats
- tests/integration/docker/tag.bats
- tests/integration/docker/test.common
- tests/integration/docker/volume.bats
These are Basic Acceptance Tests for the docker integration. They run some docker commands.
> Tests: Functional tests for docker integration

- data/container-workload.service
- data/opt-rootfs-sys.mount
These changes were left out during the initial commit
> Sync changes from the clr-systemd-config project

- tests/functional/common.bash.in
- tests/functional/help.bats
- tests/functional/state.bats
- tests/functional/version.bats
> Bats tests fixes

- tests/data/state-mounts-no-mount-destination.json
- tests/data/state-mounts-no-mount-directory_created.json
- tests/data/state-no-mounts.json
- tests/state_test.c
> Tests: add missing mount tests to state

- tests/integration/docker/volume.bats
This tests create a docker volume and verify that it is attached to
a clear container correctly.
> Tests: Verify that attaching a volume to a container works correctly

- README.rst
Fix issue that "DESIGN.rst" was not linked from "README.rst".
> Docs: Add a link to the design document.

- data/cc-oci-runtime.sh.in
- src/oci.h
- tests/data/state-mounts-no-mount-destination.json
- tests/data/state-mounts-no-mount-directory_created.json
- tests/data/state-no-annotations.json
- tests/data/state-no-bundlePath.json
- tests/data/state-no-console-path.json
- tests/data/state-no-console-socket.json
- tests/data/state-no-console.json
- tests/data/state-no-id.json
- tests/data/state-no-mounts.json
- tests/data/state-no-ociVersion.json
- tests/data/state-no-processPath.json
- tests/data/state-no-vm-object.json
- tests/data/state.json
- tests/functional/common.bash.in
- tests/runtime_test.c
> Reduce length of runtime dir

- DESIGN.rst
The DESIGN doc covered unit tests, but did not mention functional or
integration tests.
> Docs: Added details of functional and integration tests.

- tests/integration/docker/volume.bats
Couple of tests that bind-mount a single file and a
directory to a container.
> Tests: Add tests for bind-mounting files and directories

- Makefile.am
- tests/metrics/README.md
- tests/metrics/common/test.common
- tests/metrics/density/docker_cpu_usage.sh.in
- tests/metrics/density/docker_memory_usage.sh.in
- tests/metrics/run_docker_metrics
- tests/metrics/run_docker_metrics.dat
- tests/metrics/workload_time/cor_create_time.sh.in
- tests/metrics/workload_time/docker_shutdown.sh
- tests/metrics/workload_time/docker_workload_time.sh
These metrics tests allow every development to test the effects of
their patches.
> tests: add new metrics tests

- Makefile.am
- proxy/README.md
- proxy/api/fdpassing.go
- proxy/api/fdpassing_test.go
- proxy/proxy_test.go
- tests/mock/hyperstart.go
I've done a few tweaks to address James review comments that weren't captured as their own issue.
In doing so, discovered a race in the mock hyperstart that I fixed.
> Proxy review comments

- tests/integration/docker/exec.bats
These tests are for the exec functionality in docker
and the terminal test will verify that the change
of the terminal size in a container is properly
done
Signed-off-by: Cervantes Tellez, Gabriela gabriela.cervantes.tellez@intel.com
> Tests: Exec functional tests

- src/process.c
Add additional checks for file descriptor manipulation.
> Process: Check shim setup return values.

- tests/helpers/test-campaign.sh
This PR: 
1. adds a verification to check if `$GOPATH` environment variable is set
2. fixes number of tests reported.
3. adds `make install`  before running docker tests
4. adds sudo for running docker integration tests.
> test: fixes on test-campaign.sh

- .ci/ci-setup.sh
- packages.json
- vendor/github.com/hyperhq/runv/LICENSE
- vendor/github.com/hyperhq/runv/NOTICE
- vendor/github.com/hyperhq/runv/README.md
- vendor/github.com/sameo/virtcontainers/LICENSE
- vendor/github.com/sameo/virtcontainers/README.md
- vendor/github.com/sameo/virtcontainers/hyperstart/hyperstart.go
- vendor/github.com/sameo/virtcontainers/hyperstart/mock/hyperstart.go
- vendor/github.com/sameo/virtcontainers/hyperstart/mock/misc.go
- vendor/github.com/sameo/virtcontainers/hyperstart/mock/rand.go
Let's make sure the runtime and tests don't depend on a potentially changing upstream virtcontainers by vendoring the 2 packages we depend on.
> virtcontainers vendoring

- shim/shim.c
We were doing a few things wrong:
- The local pty handed out by docker hasn't been configured to do
anything special, it's a "default" canonical terminal with the line
discipline configured to line buffer input, display a local echo and
send signals on ctrl+c, ...
- We had ported a bit of code from runv to locally buffer the input on
top of the above. Unfortunately that wasn't helping and was intended
for something else in runv (telnet client for debugging)
So, the strategy to solve the input with cc-shim is as follow:
- Configure the local pty in raw mode. The goal here is to just
forward the raw content of stdin to the pty allocated for the
process inside the VM. The process inside the VM will have the pty
there configured as it wishes (canonical Vs raw) and we bypass the
treatment of …
> shim: Fix stdin handling

- .ci/ci-setup.sh
- Makefile.am
- configure.ac
- src/network.c
- src/oci.c
- src/process.c
- src/spec_handler.c
- tests/network_test.c
- tests/oci_test.c
- tests/process_test.c
- tests/spec_handler_test.c
- tests/test_common.c
- tests/test_common.h
> Tests: Add missing unit tests

- tests/integration/docker/swarm.bats
It will verify that each hostname of the replicas is always different.
> Functional test for swarm

- src/oci.c
kill command shouldn't send 'killcontainer' command to hyperstart
because cc-shim doesn't receive that signal hence cc-shim never ends.
with this patch kill command sends a kill signal to cc-shim
and cc-shim sends killcontainer to hyperstart.
> cor: Fix kill command

- tests/integration/docker/swarm.bats
Modification of the path of test-common.bash
> Tests: Modification of the source (test-common.bash) for swarm testing

- src/proxy.c
Sometimes when cc-proxy sends only out-of-band
data cor tries to convert it to big endian
returning a negative value that is used to
append the iov buffer to msg_received
causing a crash (segment default)
To fix that crash this patch validates that
messages read from cc-proxy are not out-of-band data.
> cor: Fix read out-of-band data

- tests/integration/docker/swarm.bats
These tests will verify that:
1. A ping in the replicas can be done using the overlay ip
2. All replicas have two interfaces
3. All replicas have a service ip
4. A ping in the replicas can not be done using the gateway ip
> Testing: Addition of swarm tests

- src/logging.c
- src/logging.h
- src/process.c
- src/proxy.c
- src/state.c
- src/util.c
- src/util.h
- tests/util_test.c
This PR adds error handling to some functions:
create: Before open console check if is not NULL
log: Add error handling in log setup for hypervisor
process: close duplicated shim fds explicitly
process: handle errors errors in cc_oci_setup_child
> error handling

- tests/integration/docker/run.bats
This tests are to check issue #171
They are using the run command
> Tests: Validation for the stdout and stderr

- tests/process_test.c
This patch fixes a random issue for cc_oci-setup_shim unit
tests.
The issue was caused because a new function parameter
was added but the function definition was not updated
in the unit test. As a result the new parameter value
(int shim_flock_fd) got random values because was not properly
initialized and the test failed when the value was negative.
The function definition is updated according to the function
signature.
> tests: fix cc_oci_setup_shim test

- shim/shim.c
Signed-off-by: WANG Chao <wcwxyz@gmail.com>
> shim: atexit returns 0 if successful

- tests/integration/docker/run.bats
> tests: Add docker test for handling stdin from pipe.

- proxy/proxy.go
The -pprof flag will make the proxy server profiling data overt HTTP.
A nice benefit from having this is that we can always ask for the
backtraces of all goroutines:
http://localhost:6060/debug/pprof/goroutine?debug=2
This is very handy to debug odd things happening to the proxy and check
we don't have a goroutine blocked somewhere.
> proxy: Add a way to serve pprof data over HTTP

- shim/shim.c
- src/pod.c
This patch fixes all current security issues reported by
scan tools
> security: Fixed security issues reported by scan tools

- src/oci.c
> oci: Remove spurious line of code in comment

- tests/integration/docker/cp.bats
> Test: Check that files in /etc are not zeroed out after docker cp

- tests/integration/docker/swarm.bats
- Integration of a function that will verify that swarm is not
running previously or finishing it correctly
- Use of the nginx image for swarm testing
- Check that the replicas' names are different test disable
> Tests: Modification to the swarm tests

- NEWS
- configure.ac
2.1.0.rc.4:
- Added mount namespace creation
- Added functional test tap output
- Added remaining exec tests
- Added locally runnable CI static tests
- Fixed proxy file descriptor leak
- Fixed swarm tests
- Fixed coverity reported security issues
Shortlog:
08a77d8 tests: Ensure we don't leak fds in the proxy tests
2c55083 proxy: Close VM object when detecting the end of the VM process
14aa150 tests: Synchronize the goroutine sending the READY packet
3b46cc1 tests: Close the file returned by allocateIO
b493bf3 tests: Fix "attatched" typo
0b66e77 tests: Add a generic fd leak detector
9db7025 Test: Ensure that the name of a replica is not empty
2ceb18e Test: Check that files in /etc are not zeroed out after docker cp
c1ed70b Tests: Modification to the swarm tests
1d32b9c namespaces: enable …
> 2.1.0-rc.4 release

- tests/integration/docker_images/popular-containers-images.bats
> tests: unskip tests for docker images blocked by #318

- tests/integration/docker/swarm.bats
When swarm test runs in a system with multiple network interfaces
it fails since we have to specify what interface it can use
This patch fixes this issue looking for a interface in
/sys/class/net/
> tests: add support for multiple interfaces in swarm test

- tests/integration/docker/env.bats
> tests: Add docker test to check environment.

- tests/integration/docker_images/popular-containers-images.bats
images
Enable tests that were blocked by issue 222
Update tests (addition with --rm option)
> Tests: Enable tests that were blocked and update for popular containers

- tests/integration/docker/env.bats
> tests: Unskip environment test as issue #324 has been resolved.

- CONTRIBUTING.md
- DESIGN.rst
A few amendments to the guidelines to contribute to the project now that we have Go in the same repository.
> Update coding for proxy + shim

- tests/integration/docker/attach.bats
This will verify that attach is working properly
> Test: Check attach functionality

- tests/integration/docker_images/popular-containers-images.bats
> tests: Unskip tests for images for all issues resolved in 2.1 so far.

- Makefile.am
> make: Add test-program to check -race is supported with go

- .travis.yml
> ci: Send Travis notifications to Slack

- Makefile.am
> docs: Distribute all documentation.

- documentation/architecture.md
All links were pointing to the topic branch, they should
point to master.
> documentation: Fix all links

- documentation/Installing-Clear-Containers-on-Ubuntu.md
Add installation instructions for Ubuntu
> Documentation: Add installation instructions for Ubuntu

- tests/integration/docker/dns.bats
This tests will verify the hostnames, server and ip address
> Test: Add DNS tests using Swarm

- tests/integration/docker/mtu.bats
- tests/lib/test-common.bash.in
This test will check the mtu values from the different interfaces
> Test: MTU tests using Swarm

- tests/integration/docker/dns.bats
- tests/integration/docker/mtu.bats
Remove this option in order that it does not shows all containers
> Test: Remove all function from docker ps

- documentation/Installing-Clear-Containers-on-Fedora-25.md
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
> documentation: add fedora installation details

- documentation/Installing-Clear-Containers-on-RHEL.md
Installation procedures in order to setup cc-oci-runtime in RHEL
> Documentation: cc-oci-runtime on RHEL

- src/main.c
> logging: Add version details to log file

- tests/metrics/README.md
- tests/metrics/map_mem.sh
This tool will report the memory map of a process
in JSON file. Each mapping has the next information:
- Proportional set size
- Shared memory
- Private memory
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>
> tests/metrics: Add tool for memory mapping

- tests/metrics/run_docker_metrics
- tests/metrics/workload_time/docker_workload_time_stress.sh
- tests/metrics/workload_time/kernel_boot_time_stress.sh
add scalability tests for boot time and time to execute a workload
Signed-off-by: Abraham Duenas <abraham.duenas@intel.com>
> add scalability tests

- .ci/ci-setup.sh
- installation/installation-setup.sh
- installation/rhel-setup.sh
- versions.txt
These scripts will install all the pre-requisites in order
to run cc-oci-runtime in RHEL
> Installation of cc-oci-runtime in RHEL

- src/process.c
If the execvpe call for invoking hook fails, we log the failure.
We should exit cleanly with non-zero exit status here, instead of
calling abort here which causes a core dump.
> hooks: If the exec call for a hook fails, exit with failure.

- tests/metrics/network/network-metrics-iperf3.sh
This script will measure jitter, bandwidth, bidirectional bandwidth
for local to remote and remote to local using iperf3.
> Metrics: Network Measurements using Iperf3

- tests/metrics/network/network-metrics-iperf3.sh
Combine two almost identical function/tests.
Add brief description comments
> 20170406 iperf3 metric fixes

- tests/metrics/network/network-metrics.sh
Fix a typo error in a test, combine two near identical tests, and add some small comments to the file.
> 20170406 net metric fixes

- tests/metrics/network/network-metrics-iperf3.sh
This will try to improve readability of the commands of this script
> Metrics: Improve readability

- tests/metrics/network/network-metrics.sh
This will separate the client and server commands as well as other
modifications
> Metrics: Improve readability for iperf2 metrics

- tests/metrics/network/network-nginx-ab-benchmark.sh
This will measure the requests per second from an
nginx container and the host running the apache
benchmarking tool
> Metrics: Network test using nginx and ab

- configure.ac
- data/hypervisor.args.in
- documentation/Using-OVS-DPDK-and-COR.md
- src/hypervisor.c
- src/networking.c
- src/networking.h
- src/oci.h
This pull request adds the cc-oci-runtime changes necessary for enabling host-based OVS-DPDK, as well as some documentation on setting up OVS-DPDK on the host.  Note, this is for ovs-dpdk-poc branch, not master.
> OVS DPDK enabling

- documentation/Installing-Clear-Containers-on-RHEL.md
This document will show the user the steps to install cc-oci-runtime
> Documentation: Install cc-oci-runtime on RHEL 7.3

- Makefile.am
- tests/metrics/network/network-metrics-cpu-consumption.sh.in
This test will measure the cpu % consumption while running
the bandwidth network test using iperf2.
> Metrics: CPU % consumption for network

- tests/metrics/network/network-metrics.sh
Remove iperf2 metrics as they are already implemented
using iperf3 (see #781)
> Metrics: Remove iperf2 tests

- tests/metrics/network/network-latency.sh
This will measure latency when we do a ping
from one container to another (docker <-> docker)
> Metrics: Latency measurement

- documentation/Installing-Clear-Containers-on-ClearLinux.md
> docs: Update Clear Containers installation in Clear Linux

- proxy/proxy.go
In case two requests for serving clients come in at the same time, using a mutex synchronization primitive to guarantee that both requests do not get the same client ID
> Prevent race condition with new client ID

- documentation/Installing-Clear-Containers-on-Centos-7.md
- installation/rhel-setup.sh
Change to the installation procedure for centos 7.0 and
changes in the installation script in order to support 2.1.9
Fixes #926.
> Changes to installation documentation for Centos

- tests/metrics/network/README.md
Add readme for tests/metrics/networking.
Fixes #931.
> Docs: Add readme for networking tests

- .pullapprove.yml
iphutch will help rcaballeromx and mltullis to review the
documentation on this repository.
> pullapprove: Add documentation reviewer

- Makefile.am
- tests/metrics/network/README.md
- tests/metrics/network/network-metrics-memory-pss-1g.sh.in
Measure of the proportional set size memory while doing
a transfer rate of 1Gb using nuttcp.
> Metrics: PSS for a transfer rate of 1Gb

- .ci/ci-pre-checks.sh
- .ci/ci-setup.sh
Use the new "checkcommits" program in the "tests" repository
to perform basic checks on PR commits, such as:
- Subject
- Contains a subsystem.
- Length is within prescribed limits.
- Body
- Contains a "Fixes #XXX" comment.
- Line lengths are within prescribed limits.
Unlike the original implementation (#873), "checkcommits" should
be more robust.
Fixes #872.
> CI: Perform basic checks on PR commits.

- src/pod.c
- tests/pod_test.c
The CRI-O code base went through renaming. All "ocid" instances
were replaced with "cri-o", including the annotation namespaces.
We fixed this and added proper annotations namespaces for CRI-O,
prefixed with io.kubernetes.cri-o.
This patch tries makes our current code base support both the new
and the legacy namespaces.
Fixes #960
> pod: Support new CRI-O namespaces

- data/obs-packaging/clear-containers-image/wd/debian/changelog
Clear Containers Image updated and released in OBS.
> build: obs: Update obs changelog for clear-containers-image

- data/hypervisor.args.in
- src/hypervisor.c
- src/mount.c
- src/mount.h
- src/oci-config.c
- src/oci.c
- src/oci.h
- src/pod.c
- src/proxy.c
- src/runtime.c
- src/state.c
- src/util.c
- src/util.h
- tests/data/state-mounts-no-mount-destination.json
- tests/data/state-mounts-no-mount-directory_created.json
- tests/data/state-no-annotations.json
- tests/data/state-no-mounts.json
- tests/data/state.json
- tests/functional/common.bash.in
- tests/hypervisor_test.c
- tests/integration/docker/cp.bats
- tests/mount_test.c
Check for devicemapper storage and use the underlying block device instead of overlay file system.
> Devicemapper storage

- .ci/ci-setup.sh
- installation/installation-setup.sh
- installation/rhel-setup.sh
> Fix unnecessary bash-isms in installation script

- configure.ac
- artifacts: Remove OBS common artifacsts between 2.x and 3.x
- versions: Update kernel and image versions
- Tests: Change nginx image for swarm tests
- install: Extract autoconf-archive install to separate script
ef8144e artifacts: Remove OBS common artifacsts between 2.x and 3.x
73e28fe versions: Update kernel and image versions
3a9e3d7 Tests: Change nginx image for swarm tests
82cfb1f install: Extract autoconf-archive install to separate script
Clear Containers 2.2.2 is compatible with Docker v17.05.0-ce
Clear Containers 2.2.2 support the OCI Runtime Specification [1.0.0-rc5][ocispec]
Clear Containers 2.2.2 requires at least Clear Linux containers image [16180][clearlinuximage]
Clear Containers 2.2.2 requires at least Clear Linux Containers  kernel 4.9.35-76
- [Centos][centos]
- …
> release: version 2.2.2

- documentation/Using-SRIOV-and-COR.md
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
> SRIOV: Add Documentation
