01org/cc-oci-runtime

Makefile.am
data/hypervisor.args.in
src/hypervisor.c
src/networking.c
src/networking.h
src/oci-config.c
src/oci.h
src/process.c

This PR adds support for two modes of docker networking (bridge and none).
This includes
- Discovering the docker CNM created network interface
- its IPv4, IPv6 and MAC address
- Sending IP Configuration Parameters into the guest kernel
- Sending in the hostname to the guest kernel
- Creation of a single tap interface that can be used to
connect the VM to a single container network
- Configuration of the MAC address via QEMU
- Quick and dirty implementation that creates and integration
bridge and connects it to the container interface (veth)
and the tap interface (tap)
- Reprogramming of the veth MAC to one that does not conflict
with the MAC that is now assigned to the tap within the VM
Limitations:
IPv4+IPv6 containers are not supported due the kernel command
line limitations.
This …

Adding basic networking support

---

configure.ac

Check for libnetlink header and library in configure.ac.
This library is shipped by iproute2 and is needed to
compile network module.
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

configure.ac: add libnetlink check from iproute2

---

INSTALL_DOCKER.rst

* In order make cc available and not lose configuration settings in the
next upgrade of docker, we must create "our" systemd driver.conf to
overwrite default configuration shipped by the package.
* Downloading images of clearcontainers should always point to the latest
image released, with the change introduced here we make sure the user
download the latest cc image.

DOCS: custom docker systemd, cc-image download

---

INSTALL_DOCKER.rst
README.rst

* Add a dependency needed to build cc-oci-runtime: iproute2-dev

DOCS: Add iproute-dev dependency to build cc-oci-runtime

---

src/hypervisor.c

This patch reduces code lines and makes code simpler and readable.
This patch won't decrease the calls to cc_oci_replace_string.

Simplify hypervisor tag processing code by tabulating data

---

src/hypervisor.c
tests/hypervisor_test.c

When a word begins with '#' that word and all remaining characters
will be treated as comments (will be ignored)
example:
input text:
```
line #comment
#comment
line#
line#text
line\#text
line #
line # comment
line \# #comment
```
Result:
```
line
line#
line#text
line\#text
line
line
line \#
```
Fixes #35

Add support for comments in hypervisor.args

---

.travis-setup.sh
.travis.yml

travis: resolved dependencies to build cc-oci-runtime
needed to build glib, json-glib and libcheck from sources
still have some issues with unit tests that need to investigate
and resolve before adding those checks to travis.

travis: resolved dependencies to build cc-oci-runtime

---

tests/hypervisor_test.c

In commit:
commit 396ff49a635916c784b95c49e53cd6e408fd9321
Author: Archana Shinde <archana.m.shinde@intel.com>
Date:   Fri Jul 29 17:40:23 2016 +0000
Redirect stdio to the containerd provided pseudoterminal for console
case.
The console device was changed, but not the corresponding unit test. Fix
that.

tests: Fix the cc_oci_expand_cmdline() test

---

configure.ac

Latest ubuntu and hence travis does not support libnetlink.
Remove the libnetlink dependency for now

Networking: Remove netlink dependency

---

configure.ac

We need glib 2.44+ for g_option_context_set_strict_posix(), so state
that if the glib pkg-config configure check fails.

Config: Explain why specific glib version required.

---

configure.ac

When testing the build with the minimum requirements we declare, I
discovered G_FILE_MONITOR_WATCH_MOVES wasn't properly documented and was
introduced during the 2.45 cycle. The minimum requirement for glib is
then 2.46.
The glib documentation patch is on its way:
https://bugzilla.gnome.org/show_bug.cgi?id=769630

build: Bump the glib requirement to 2.46

---

configure.ac

cc-oci-runtime is not using a specific functionality
of check-0.9.4+

remove explicit version of check

---

README.rst

Currently supported Docker networking modes are "--net=bridge" (default)
and "--net=none".

DOCS: Update details on networking limitations.

---

.travis.yml

This reverts commit 96e9174b3ab1132ef807e35be8e7445aba109aca.
We didn't envision something obvious in retrospect: when forking this
git repo and pushing branches for testing, travis doesn't trigger
anymore. Not very handy.

Revert "CI: Only run Travis on the master branch."

---

Makefile.am

Nicer builds are all the rage.

build: Use AM_V_GEN when generating the commit_id file

---

Makefile.am

File "cc-oci-runtime.sh.in" was erroneously added to defaults_DATA
meaning it was being installed to the data directory.
Ensure the file is distributed, but not installed.

Build: Don't install "cc-oci-runtime.sh.in".

---

.travis-setup.sh
.travis.yml

Clang often does a better job of finding issues compared to gcc.
Further, not all distros will be using gcc so attempt to build for
both compilers to ensure we support both.

CI: Run Travis build with clang as well as gcc.

---

.travis-setup.sh
.travis.yml
Makefile.am
src/commands/create.c
src/commands/ps.c
src/commands/run.c
src/oci.h
src/process.c
tests/hypervisor_test.c
versions.txt

Another step towards better CI:
- Get rid of warnings and make sure we don't introduce any later on
- Run make check
What's still to do is documented in https://github.com/01org/cc-oci-runtime/issues/69

Enable make check (unit tests only) and check for warnings in travis

---

src/logging.c
src/logging.h
src/main.c
tests/annotation_test.c
tests/hypervisor_test.c
tests/json_test.c
tests/logging_test.c
tests/mount_test.c
tests/namespace_test.c
tests/oci-config_test.c
tests/oci_test.c
tests/priv_test.c
tests/process_test.c
tests/runtime_test.c
tests/spec_handlers/annotations_test.c
tests/spec_handlers/hooks_test.c
tests/spec_handlers/linux_test.c
tests/spec_handlers/mounts_test.c
tests/spec_handlers/platform_test.c
tests/spec_handlers/process_test.c
tests/spec_handlers/root_test.c
tests/spec_handlers/vm_test.c
tests/state_test.c
tests/util_test.c

with this patch enable_debug will be encapsulated
in cc_log_options struct, now enable and disable
debug logging is easier and extern references to
enable_debug are not more needed

Logging: remove enable_debug from main file

---

INSTALL_DOCKER.rst

On build 9890 clear-containers 2.0 is insallable with Bundles, the basic
component of Clear Linux to install software. There is no need to
compile or download rpms anymore.

Update doc to install clear-containers 2.0 on Clear Linux.

---

README.rst
src/logging.c
src/logging.h
src/main.c
src/process.c

Currently hypervisor's stdout and stderr are ignored. This makes
hard to debug a hypervisor.
This patch adds --hypervisor-log-dir option that can be used to enable
hypervisor logging and specify the directory where hypervisor logs
will be created.
With this patch hypervisor's stdout and stderr will be saved into
${hypervisorLogDir}/${containerId}-hypervisor.stdout and
${hypervisorLogDir}/${containerId}-hypervisor.stderr respectively.
fixes #71

Logging: Capture hypervisor's stdout and stderr to a file

---

.travis-teardown.sh
.travis.yml

Added an "after_failure" script to display all testsuite-generated log
files on build failure.

CI: Show tests logs on Travis failure.

---

INSTALL_DOCKER.rst

A range of small improvements to the INSTALL_DOCKER.rst file.
- remove un-used doc links
- remove the remaining Attention box
- add a missing 'sudo'
- bump the out of date CLR version number
- Add example outputs for the docker commands
- clean up 'root' and # promts
- remove newgrp usage for logout instead

DOCS: Improvements to the INSTALL_DOCKER

---

README.rst

The "--global-log" option used to be enabled by default. However, this
is no longer the case (see commit 63549d5), so update "README.rst" to
reflect the current behaviour.

Docs: Remove out-of-date global-log details.

---

CONTRIBUTING.md

Make some expansions and additions to the CONTRIBUTING document,
including:
- subject: prefixes on patches
- Add a link to the Linux Kernel SubmittingPatches doc
- Note about PRs, reviews, updates and force pushing

DOCS: Add more details to the CONTRIBUTING document

---

.pullapprove.yml

The pullapprove.com "approve_regex" value must be a single-quoted
string.

Process: Fix pullapprove config.

---

src/networking.c

Previously, we only logged the name of the command that failed to run,
but this isn't sufficient to diagnose problems.

Network: Log error if network setup fails.

---

.travis-setup.sh

In:
commit e7344c94314982e3c50ddee5e1552a6aa4be87dd
Author: James Hunt <james.o.hunt@intel.com>
Date:   Thu Aug 11 12:36:35 2016 +0100
CI: Run Travis and Coverity using "make -j5".
we add -j5 to the runtime build, but the review missed that we could
also do it for the deps. Fix that!

travis: Speed up compilation of the deps as well

---

.pullapprove.yml

The current regular expression only includes the "emoji" version of
"+1", so add a non-emoji equivalent.

Process: Add basic "+1" to pullapprove config.

---

src/hypervisor.c

Enable vhost_net support to increase the networking performance.
vhost_net moves part of the Virtio driver from the userspace into the
kernel. This reduces copy operations, lowers latency and CPU usage.
This closes https://github.com/01org/cc-oci-runtime/issues/161

Networking: Enable vhost_net support

---

README.rst
src/hypervisor.c

Explicitly set the network device to virtio-net-pci.
Note: On the host you need a kernel with CONFIG_VHOST_NET=y and
in the guest you need a kernel with CONFIG_PCI_MSI=y

Networking: Explicitly set the network device to virtio-net-pci

---

src/hypervisor.c
src/networking.c
src/networking.h
src/oci-config.c
src/oci.h
src/process.c

Discover all the interfaces and their associated IP addresses
within the container name space. Connect each interface to the
a integration bridge and create an associated tap interface
for qemu.
Pick the first interface discovered and configure its IP address.
Note: This IP configuration is currently incorrect when there are
multiple interfaces.
This is partial support for issue https://github.com/01org/cc-oci-runtime/issues/95

Networking: Add support for discovery of multiple interfaces

---

.travis.yml

Coverity Scan is unable to access an encrypted
"COVERITY_SCAN_NOTIFICATION_EMAIL" variable, so try with an unencrypted
one to ensure it can handle any type of variable for the notification
email address.

CI: Use standard env var for Coverity email address.

---

.travis.yml

It should be possible to specify the Coverity notification email using
environment variable COVERITY_SCAN_NOTIFICATION_EMAIL (standard,
encrypted, or repository type).
However, the Travis logs show this variable is silently unset
before Travis passes the information to the Coverity addon.
Hence, to enable any form of Coverity Scan checking, we must specify
"addons.coverity_scan.notification_email" for now.

CI: Revert to specifying notification email using "notification_email".

---

.travis-setup.sh
Makefile.am
README.rst
configure.ac
src/netlink.c
src/netlink.h
src/networking.c
src/process.c

Create all the network interfaces using netlink sockets. This will reduce the latency associated with the interface configuration/creating (as compared to invoking the ip utility). This also reduces the dependency on the distribution on which the runtime runs. 
Note: libmnl is now a required dependency on the host system.
Please merge https://github.com/01org/cc-oci-runtime/pull/167 before merging this to get a better view of the actual changes introduced by this PR.

Networking: Use Netlink to discover and configure interfaces

---

src/logging.c

This fd needs to be closed on success and failure; the former because
it has been dup(2)'d, and the latter because the dup(2) failed but the
fd is still open from the original creat(2).

Logging: Fix "std_file_fd" fd leak.

---

configure.ac

Code is unreachable as it's a comment and its presence is confusing.

Config: Remove commented-out code in configure.ac

---

Makefile.am

"bats_test_sources" did not include all the bats tests in the
repository, and hence only a subset were being included in a "make
dist" archive.

Tests: Ensure all bats tests are distributed.

---

src/mount.c

Fixes #205
Fix cppcheck :  Return value of allocation function 'creat' is not stored .

mount: fix cppcheck error, close fd

---

src/networking.c

Fix missing break in case statement which causes IPv6 prefix
generation failure.

Networking: Fix missing break in prefix logic

---

configure.ac

To avoid having to regenerate the "vm.json" configuration file,
"--with-cc-image=" is often provided with a symlink path [1]. This allows
other mechanisms to update the image and "re-point" the symlink to the
latest image, which avoids having to regenerate "vm.json".
However, configure was resolving kernel and container paths, meaning
that the runtime would not be using the latest image (as specified by
the symlink) and would fail if the release hard-coded in "vm.json" was
removed when it became stale.
Note that the runtime full resolves all paths so that it can log
full details of the artifacts being used for a particular container.
--
[1] - The same logic applies to "--with-cc-kernel=" but note that
"--with-qemu-path=" is not resolved.

Config: configure must not resolve kernel and container image paths.

---

Makefile.am
configure.ac
data/container-workload.service
data/container.target
data/opt-rootfs-proc.mount
data/opt-rootfs-sys.mount
data/opt-rootfs.mount
src/oci.h
tests/oci_test.c

Fixes #170 
Clear containers internal behivor is configured by systemd
services. This patch adds the systemd services that must
be intalled in a container image.
Added configuation units:
container.target           : unit that groups and sync all task to be done at
clear container boot time.
container-workload.service : unit that execute initial container
workload in a shared rootfs.
opt-rootfs.mount           : mount shared rootfs to be used in the
container workload
opt-rootfs-proc.mount      : mount /proc guest in shared rootfs
opt-rootfs-sys.mount       : mount /sys guest in shared rootfs

data: Distribute container image init services

---

tests/integration/docker/network.bats

This test runs a simple ping from one Container to another
to verify connectivity.

Tests: add connectivity test between two containers

---

Makefile.am

Add files under tests/integration/ to distribution tarballs.

Tests: newly-added integration tests are not distributed.

---

src/hypervisor.c
src/oci.c
tests/hypervisor_test.c

Currently we check if stdin refers to a terminal using isatty()
Use the process.terminal value from config.json instead.
Docker sets this value to true when run interactively.
Fixes 183

oci: Use process.terminal to check for interactive runs

---

src/oci.c
tests/oci_test.c

An unintended side-effect of commit 26559c5 was that it broke running
standalone. Although running stand-alone still requires "config.json" to
specify "process.terminal=true", cc_oci_start() was not waiting for the
hypervisor.
This minimal fix [1] is better than what we had before 26559c5 since it
moves the heuristic to the generic cc_oci_config_update() rather than
hard-coding it in cc_oci_start().
---
[1] - An alternative solution would be to add "process.terminal"
to the state file.

Process: Fix running standalone.

---

src/process.c
tests/process_test.c

The fix introduced on 3d8911d since although it supported no-arg hooks,
it did not support running hooks where the argv[0] passed to the hook
was different to the hook path. This is used by docker to handle network
setup where dockerd is exec'd as "libnetwork-setkey".
The correct fix is to re-introduce the use of
G_SPAWN_FILE_AND_ARGV_ZERO and handle the "no-arg" case specially (along
with adding better comments around arg handling and the use of
G_SPAWN_FILE_AND_ARGV_ZERO).
Updated tests to reflect re-introduction of G_SPAWN_FILE_AND_ARGV_ZERO.
Note that these tests are still commented out since they fail under
valgrind's helgrind tool. See github issue #214.

Process: Re-take on fixing running hooks with no arguments.

---

src/main.c

handle_arguments() was calling cc_oci_get_priv_level() but not returning
false in the failure scenario as it should have.

Arguments: Fail if privilege checks fail.

---

configure.ac

The address specified in "configure.ac" is not that useful given that
there is now a mailing list that could be used instead, as specified in
CONTRIBUTING.md. However, that document already explains how we want
bug reports to be handled (github issues) so a bug report address is
redundant.

Config: Remove bug report email address.

---

README.rst

remove -d option from create cmd line
fixes #232

docs: match README with code implementation

---

tests/functional/help.bats

A rogue "@" had crept into the description for the "kill --help" bats
test.

Tests: Fix bats test description.

---

src/commands/help.c

The Usage string inferred that you could place any options any side
of the [command], but what it meant to indiate was that global options
come before the command and command specific options come after the
command. Change the message to make that clearer.
Ideally we would also modifiy the 'Options:' paragraph section in the
help to say 'Global Options:', but that is buried in the source of the
glib g_option source, with no way to override.
Fixes #242

cmdline: Clarify where you can place global and command options

---

.pullapprove.yml

The QA team are now running additional tests which are triggered when
new PRs are raised. The test outcome is marked by adding a special
comment to the PR:
- a "qa-passed" comment means all the tests passed.
- a "qa-failed" comment means atleast one test failed.
Updated the pullapprove configuration file to:
- Require an additional approval from named QA members.
- Allow a PR to be explicitly rejected by introducing use of the
`reject_regex` option containing `qa-failed`
(if any QA tests fail, the PR cannot be approved).
- Modified the `approve_regex` to add `qa-passed` and changed `Approve`
to `Approved` to mirror the `reject_regex`'s `rejected` value.

Process: Add QA check to pullapprove config.

---

src/mount.c
src/oci.h
src/state.c
tests/data/mounts.json
tests/data/state.json

with this patch directories created by cc-oci-runtime
when directories or files are mounted will be deleted
once umount is done
fixes #178

Mount: leave rootfs as it was found

---

src/oci.c

The child process that becomes the hypervisor updates the on-disk state
file, so the parent process (the runtime) must re-read the state file to
reflect the true state.
This fixes the "run" command and the failing functional tests in "start.bats".

State: Make runtime re-read statefile last updated by child.

---

tests/namespace_test.c

The test_cc_oci_ns_setup() test asserts the possible errno values when
cc_oci_ns_setup() fails. However, EPERM was missing, which gets returned
when the tests are run as a non-priv user under docker.

Tests: Fix failure when running under docker.

---

src/oci.c
src/oci.h
tests/data/passwd
tests/oci_test.c

HOME is provided by default by runc. Users will expect the same behaviour
from our runtime.
We first check if HOME is provided in the config provided by docker.
If not we set it to the home directory of the workload user.
Fixes #139

environment: Provide HOME in the default container environment

---

.pullapprove.yml

pullapprove doesn't currently provide the funcationality we need to
support a proper QA process, so disable the QA review group and
QA approve/reject regex's for now.

Process: Disable QA pullapprove review group.

---

src/oci.c

cc_oci_stop() was incorrectly cleaning up resources before running the
post-stop hooks.
Notes:
- This hasn't been noticed since docker doesn't provide post-stop hooks
by default.
- The functional tests did detect this error.

Hooks: Run post-stop hooks before resource clean up.

---

src/namespace.c
src/netlink.c
src/networking.c
src/process.c

We really need to run doxygen regularly.
It's also rather surprising that there is no way to make doxygen return
1 if it find files that contain doxygen comments, but which are invalid
/ incomplete as if so we could tie that into the build.

Docs: Fix outstanding doxygen issues.

---

data/container.target

Clear containers image will use hyperstart as daemon started by
hypertart.service. This patch adds this service in the boot flow.
Notice that it uses Wants=hyperstart.service in container.target
(as others services and mount units), "if the units
fail to start or cannot be added to the transaction, this has no
impact on the validity of the transaction as a whole"[1]. This means
that if a container image does not provide hyperstart.service or
fails the boot wont fail.
1. https://www.freedesktop.org/software/systemd/man/systemd.unit.html

data: guest-config: Add hyperstart.service as boot dependency

---

data/container.target

With this patch sysfs will be mounted on /sys
this change is needed by hyperstart due to it
reads /sys/class/virtio-ports/ in order to find
CTL and TTY channels

Mount: fix mount sysfs

---

src/hypervisor.c
src/hypervisor.h
src/process.c
tests/hypervisor_test.c

Dynamic arguments can be passed to the hypervisor by adding them to
an array which is appended to the static hypervisor argument list.
The static hypervisor args are constructed as before.
Fixes #219

create: Provide a way to append arguments to the hypervisor arg list

---

README.rst
data/hypervisor.args.in
src/hypervisor.c
src/oci.h

Fixes #258
This patch adds serial ports used by hyperstart using Unix socket backend

hypervisor: Add sockets for guest agent

---

Makefile.am

When we re-run configure, some Makefile variables may have changed as a
result and so we need to re-generate files potentially impacted.

build: Make the generated files depend on Makefile

---

.travis-setup.sh

Currently we output the full compilation logs of the dependencies but they don't add much value and make the travis UI sluggish.
I had to debug some issues in the travis build and the above made the job quite a pain, so decided to do something about it.

Make the travis output a bit more manageable

---

tests/data/state-mounts-no-mount-destination.json
tests/data/state-mounts-no-mount-directory_created.json
tests/data/state-no-annotations.json
tests/data/state-no-bundlePath.json
tests/data/state-no-console-path.json
tests/data/state-no-console-socket.json
tests/data/state-no-console.json
tests/data/state-no-id.json
tests/data/state-no-mounts.json
tests/data/state-no-ociVersion.json
tests/data/state-no-processPath.json
tests/data/state-no-vm-object.json
tests/data/state.json

Commit 1008fe2 included an erroneous search-and-replace that missed off
a slash, resulting in incorrect paths in the JSON files used by the
tests.

Tests: Fix incorrect paths introduced by commit 1008fe2.

---

configure.ac

The automatic bundle generation feature (commit 7dd2c5a) contained a
bug where the default automatic bundle path was relative rather than
absolute.
Now, both the default and the path specified by
"--with-auto-bundle-creation-path=" is made absolute.
Note that symbolic links are not expanded, for symmetry with
other paths passed to configure (such as "--with-cc-image=" and
"--with-cc-kernel=" where symlink expansion is expressely undesirable).

Config: Expand path for automatic bundle-generation.

---

tests/integration/docker/volume.bats

tests: remove unnecessary line from volume.bats that was making the tests to fail
when running volume.bats tests, the tests look for a volume.bash
file, which does not exists and is not necessary for the test.

tests: remove unnecessary line from volume.bats that was making the tests to fail

---

.gitignore
Makefile.am
data/run-bats.sh.in
tests/functional/README.rst

Fixes #123 
When running cc-oci-runtime as root, it configure network using
hosts interaces; This makes the host machine lose network configuration.
To avoid this, it is required to run it with network namespace unshared.
An script (run-bats.sh) is added to run functional tests. This will unshare network
namespace when running as root.

Tests: Fix bats test running as root

---

data/hypervisor.args.in

When qemu is launched with socket > 1 ("-smp" option), performance is
harmed, so "sockets" and "threads" must be 1. The other values can
change (and should ideally match the cpu count on the host system).

Config: Set sockets=1 for qemu.

---

src/oci.c
tests/oci_test.c

The correct way of determining if we are being run by conatinerd during
start phase is to check if no tty is attached to stdin. We should'nt
be checking for config.terminal value as this refers to the stdin terminal
for the create phase.
Revert earlier changes introduced with this bug. As a side note, the terminal
value will be stored in the state file in the future to account for
the code that determines the config.terminal value programmatically.

start: Correct how we determine if the runtime is being run standalone

---

m4/ax_valgrind_check.m4

By dropping the equals sign ("define name" rather than "define name ="),
multi-line variables can be used with $(eval) under make 3.81 (as
provided by Ubuntu Trusty).
The effect of this is that the valgrind build will now run under Travis,
which uses Trusty.

CI: Fix running valgrind under Travis.

---

src/process.c

Add missing check for cc_oci_vm_launch() parameter.

Process: Add missing parameter check.

---

proxy/proxy_test.go
tests/mock/hyperstart.go

Export sendMessage method as public method, and remove the automatic sending of READY message after the mock receive a client connection on CTL channel.
This change allows mock client to simulate sending of a message from hyperstart on CTL channel.

Make mock hyperstart more flexible

---

Makefile.am
configure.ac
data/dockerFiles/Dockerfile.clearlinux
data/dockerFiles/Dockerfile.fedora.in
data/dockerFiles/Dockerfile.ubuntu.in
data/dockerFiles/README.md
versions.txt

These Dockerfiles for Clear Linux, Fedora and Ubuntu contain
all dependencies needed to build cc-oci-runtime from sources
and launch Clear Containers as stand alone or with docker.

Add Dockerfiles to create an environment for building and testing cc-oci-runtime 

---

Makefile.am
data/cc-agent.service
data/cc-agent.target

This patch adds cc-agent.target and cc-target.service. The target
starts the clear containers guest agent (hyperstart). After the agent is finished
the VM will be powered off.
The agent output is sent to tty for debug information. Can be retrieved
by using a serial console in the guest.

data: Add cc-agent.target

---

tests/helpers/test-campaign.sh

test-campaign.sh helps to test changes on cc-oci-runtime,
it builds and runs the test suites that are contained in this
repository and gives a summary of the executed test outcomes.
summary example: 
```
Summary for unit_tests
Total Tests:  22
Passed Tests: 22
Failed Tests: 0
Skipped Tests: 0
Summary for functional_tests
Total Tests:  46
Passed Tests: 46
Failed Tests: 0
Skipped Tests: 20
Summary for valgrind_tests
Total Tests:  22
Passed Tests: 22
Failed Tests: 0
Skipped Tests: 0
Coverage Report: 
Lines Coverage: 72.4%
Functions Coverage: 78.9%
Summary for Docker Tests:
Total Tests:  24
Passed Tests: 24
Failed Tests: 0
Skipped Tests: 24
Return Codes of executed checks:
autogen return code: 0
make return code: 0
unit tests return …
```

Add test execution script for cc-oci-runtime

---

.travis-setup.sh
.travis.yml
proxy/api/api.go
proxy/api/client.go
proxy/api/common_test.go
proxy/api/fdpassing.go
proxy/api/fdpassing_test.go
proxy/api/protocol.go
proxy/protocol.go
proxy/protocol_test.go
proxy/proxy.go
proxy/proxy_test.go
proxy/syscall.go
proxy/vm.go
tests/mock/hyperstart.go
tests/mock/misc.go

Added a few linters to the travis checks:
- misspell
- go vet
- gofmt
- golint
Of course, having never run those linters on the proxy code before, it needed a few fixes here and there for everything to be green.

Go linters and the resulting proxy fixes

---

tests/mock/hyperstart.go

We had a race:
- A branch was introduced a add golint to travis
- In the mean time, a commit producing a golint error was added
The golint branch didn't have the offending commit and wasn't rebase
before merging so we didn't discover the problem until it was too late.

tests/mock: Fix golint error on SendMessage()

---

.pullapprove.yml

I don't think we want to restrict review for PRs to the master branch
but do it for PRs to any branch.
2 scenarii:
- Someone pushes commits to a branch without going through a PR, with
that one bypasses the whole PR/review mechanism (but still has
travis testing)
- A PR is opened to ask for review/permission to merge some patches in
a branch. In this case it sounds like a good idea to always go
through review/CI.

pullapprove: Require review and testing on PRs against any branch

---

tests/mock/hyperstart.go

I try to reset the net.Conn objects to nil, but that's not necessary,
and races with the code setting them to real objects.
This should fix:
==================
WARNING: DATA RACE
Read at 0x00c420010308 by goroutine 20:
github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).readCtl()
github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:133 +0x6b
github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).readMessage()
github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:150 +0xa2
github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).handleCtl()
github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:225 +0x6e
Previous write at 0x00c420010308 by goroutine 14:
github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).Stop() …

Fix 2 races in tests/mock

---

.travis/travis-build.sh

Having multiple threads running the tests also means having their output
interleaved. When a test fails it's then that much harder to figure out
what happened.
The small time gain isn't worth it.

travis: Don't run the tests with make -j5

---

shim/shim.c
shim/shim.h

Check to ensure data length value returned by proxy is positive before
using this value in a loop.

Shim: Perform check on data length returned by proxy.

---

Makefile.am

disable helgrind and drd checks when running make distcheck

disable helgrind and drd checks when running make distcheck

---

shim/shim.c

Switch to using strncpy(3) rather than strcpy(3) for safety.

Shim: Remove use of strcpy(3).

---

shim/shim.c

Since the exit code is a single char byte, use simple assignment to get
the exit code instead of atoi() call.

cc-shim: Use simple assignment to get the exit code from buffer

---

proxy/api/api.go
proxy/api/client.go
proxy/proxy.go
proxy/proxy_test.go

Archana suggested we add a containerId parameter to Bye so we don't have
to issue an attach payload to associate the connection beforehand. That
saves a round-trip with the proxy.
Because it's still early times and we don't have any user, let alone any
stable user, yet, I broke the API: the old behaviour using Bye with no
parameter when the client is already attached to a VM will not work
anymore.

proxy: Add a "containerId" argument to Bye

---

src/proxy.c

Don't call cc_proxy_disconnect() if not connected or config invalid.

Proxy: Only disconnect on error.

---

proxy/proxy.go

Remove a superfluous newline that was causing a build failure
(due to "gofmt").

Proxy: Fix gofmt newline error.

---

src/oci.c
tests/oci_test.c

The shim pid was getting passed for the vm shutdown.

delete: Pass hypervisor pid for qmp shutdown.

---

src/oci.c
src/proxy.c
src/proxy.h

On stopping a container with docker stop, bye command is issued to
the proxy. It is necessary for the runtime to esatablish connection
with the proxy before issuing bye command.

delete: Connect to the proxy before calling bye command for proxy

---

src/process.c
src/proxy.c

Add additional check to ensure the length of the hypervisor arguments
passed to the child process is within reasonable bounds.

Process: Check hypervisor argument length bounds.

---

tests/functional/common.bash.in

Previously, if certain bats helper functions failed, they would log a
message and "exit 1". This was incorrect since "exit 1" caused the
script to exit, meaning the bats framework was unaware that an error
had occured. The result was that no error output would be produced for
failing tests.
Replacing the "exit 1" with a call to false(1) results in the correct
behaviour since bats notices the failing assertion triggered by the
false result and displays the error as expected, before failing the
test.

Tests: Unbreak bats error handling.

---

.travis.yml
proxy/vm.go

This PR fixes issue #395. The code from proxy now relies on common hyperstart package instead of duplicating hyperstart implementations.

proxy: Rely on hyperstart package

---

versions.txt

Fixes: #443 
This patch adds well kown clear container image and container kernel
that work with 2.1 branch

versions: add well known image and kernel version working with 2.1 architecture

---

.ci/ci-setup.sh

qemu-lite requires the "--enable-vhost-net" configure option.

CI: Build qemu-lite with vhost support.

---

.ci/ci-teardown.sh

With this patch teardown script also will dump
the log generated by libcheck with more information
about failed tests

CI: add test-suite.log to teardown script

---

packages.json
proxy/README.md
proxy/protocol.go
proxy/protocol_test.go
proxy/proxy.go
proxy/proxy_test.go
proxy/vm.go
vendor/github.com/golang/glog/LICENSE
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go

This PR adds some tracing facilities to the proxy to help with debugging. It should have done way earlier, lesson learned.
Example with `docker run busybox ls` and maximum verbosity:
```
$ sudo ./cc-proxy -v 2
I1125 16:29:49.384830   32015 proxy.go:315] proxy started
I1125 16:29:55.250793   32015 proxy.go:59] [client #1] client connected
I1125 16:29:55.447234   32015 proxy.go:69] [client #1] hello(containerId=b97346dee717057b000e0f635c974d5fb841c18089108f7db64093b8da530f46,ctlSerial=/var/run/cc-oci-runtime/b97346dee717057b000e0f635c974d5fb841c18089108f7db64093b8da530f46/ga-ctl.sock,ioSerial=/var/run/cc-oci-runtime/b97346dee717057b000e0f635c974d5fb841c18089108f7db64093b8da530f46/ga-tty.sock
I1125 16:29:55.583992   32015 proxy.go:69] [client #1] cmd=startpod, …
```

Proxy logging

---

Makefile.am
src/oci.h

cc-shim is installed under /usr/libexec as it is not meant
to be started on its own.

config: Provide full path to the cc-shim for invoking it.

---

.pullapprove.yml

Whilst we work out some niggles with workflow, pushes, acks and QA, reduce the strictness of some pullapprove requirements.

CI: Reduce pullapprove requirements

---

.ci/ci-build.sh
.ci/ci-setup.sh

gocyclo computes the cyclomatic complexity in functions and makes sure
we don't go over a certain number, which would indicate the function is
too complicated and needs to be broken up.
The number 15 is taken from ciao. That looks like a fine number.
Fixes: https://github.com/01org/cc-oci-runtime/issues/353

ci: Add gocyclo to the build

---

src/process.c
src/proxy.c
src/proxy.h

When we run bash in interactive mode under docker, the prompt is
not shown. We can see the prompt for other shells.
A quick test using this:
https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html
shows that bash is not running in interactive mode causing the
systemwide startup files not being read and settings not
being applied resulting in PS1 variable to be empty.
The shell is not run in interactive mode because stderr is not
pointing to a terminal even though stdout and stdin are attached to
a tty by hypertstart. The reason being, hyperstart does not attach
the terminal to tty when the stderr sequence number is not set to 0.
Hence, allocate just one stream for the tty case, and explicitly set the
error sequence number to 0 with the "newcontainer" …

console: Fix missing prompt when bash is run interactively.

---

proxy/proxy.go

When not socket activated, the proxy creates the socket itself. That
socket doesn't need to be world rw, so remove those permissions.

proxy: Restrict access to the proxy socket a bit

---

src/oci.c
src/proxy.c
src/proxy.h

This patch adds kill container and destroy pod
functionalities using hyperstart commands
(killcontainer and destroypod)

cor: Implement kill container and destroy pod

---

src/process.c

A previous patch causes a docker hang trying to 
create a container, lets unlock create command.
Description:  
File descriptos 0,1,2 are close on exec.
This allow shim use stdio fd to print and read.
The fds are duplicated until its value is more
than 2.
If close the old file descriptor, next time
dup is called will get the lowest fd , and this
could be the previous closed, causing that
runtime never exit from while loop.
After this loop exec is done, and previous duplicated
fd are close on exec.

create: exit from  infinite while loop

---

packages.json
proxy/vm.go
vendor/github.com/sameo/virtcontainers/README.md
vendor/github.com/sameo/virtcontainers/hyperstart/hyperstart.go

This PR fixes issue #439.
It allows the proxy to rely on latest API defined by the hyperstart package, so that it does not need to be aware about any details of the hyperstart protocol.

proxy: vm: Improve hyperstart protocol abstraction

---

proxy/proxy.go

It's expected that cc-proxy is socket activated by systemd in
production, but, the proxy also has a path where it creates the socket
itself. This is useful for debugging as it allows people to launch the
proxy from the command line directly.
Unfortunately, we were not able to create the socket in that second
path when the /run/cc-oci-runtime/ directory wasn't already created
(systemd will do that for us in the socket activated case).
Fix this by creating the /run/cc-oci-runtime directory if needed.
Fixes: https://github.com/01org/cc-oci-runtime/issues/459

proxy: Create runtime directory if needed when not started by systemd

---

src/main.c
src/process.c
src/util.c
src/util.h

Attempting to write to a pipe without an associated reader will
by default terminate the process. Explicitly ignore SIGPIPE to
avoid that happening.

Signals: Ignore SIGPIPE to avoid being killed.

---

proxy/proxy.go

I was missing telling the user this was the hyper payload like the other
payloads.

proxy: Fix tracing messages for the hyper payload

---

src/process.c

Ensure that the specific errno value set by a write(2) error is checked.

Process: Take more care handling EPIPE.

---

src/network.c
src/network.h
tests/network_test.c

since hyperstart is in charge of the VM
the only right way to shutdown the VM is through
hyperstart's API hence qmp shutdown message is not
more needed.
This patch also fix the cppcheck error:
"The function 'cc_oci_vm_shutdown' is never used."

cor: remove unused functions

---

proxy/README.md
proxy/api/api.go
proxy/proxy.go
proxy/vm.go
src/hypervisor.c
src/oci.h
src/proxy.c
src/state.c

This PR makes the proxy able to extract the hyperstart logs out of the VM and display then along with the usual proxy tracing, that should help us debug some of the weird interactions we still have with hyperstart:
I haven't added the console path to the state on purpose as I'm not really sure it belongs to the runtime state (I'm not too sure ctl and io socket belong there either tbh). It may belong to a potential proxy state in case we want to upgrade the proxy for instance and need to read back the proxy state from disk.
The result looks like:
```
$ sudo ./cc-proxy -v 3
I1202 11:44:36.079095   10204 proxy.go:332] proxy started
I1202 11:44:44.922280   10204 proxy.go:63] [client #1] client connected
I1202 11:44:45.124991   10204 proxy.go:73] [client #1] …
```

proxy & hyperstart logging

---

tests/metrics/density/docker_memory_usage.sh.in
tests/metrics/run_docker_metrics
tests/metrics/workload_time/kernel_boot_time.sh

This PR contains 2 commits:
1. tests: add script to measure kernel boot time.
With this script, we will be able to measure the kernel
boot time when a container is launched using cc-oci-runtime.
The script uses dmesg log to get the data
2. tests: fixed condition to check if smem is installed
docker_memory_usage.sh needs smem tool to be installed in the system.
this commit fixes the condition that checks if smem is installed.

test metrics: Add script to measure kernel boot time and fix memory usage script

---

src/oci.c
src/oci.h
src/process.c

Since cc-oci-runtime must be able to run containers
standalone, start command is in charge of determinate
if shim is running or not also start command must
update state file once shim has finished.
This patch opens a file and locks it after fork and before
exec cc-shim when cc-shim ends this file will be unlocked
allowing to start command catch that event and update the state file,
this is another way to detect when a process ends.

cor: start command waits for cc-shim ends

---

src/command.c
src/command.h
src/commands/exec.c
src/oci.c
src/oci.h
src/process.c
src/process.h
src/proxy.c
src/proxy.h
tests/integration/docker/exec.bats
tests/oci_test.c
tests/process_test.c

This PR adds support for exec command. 
- Adds support for missing command options
- launch shim for an exec workload
- adds execmd function request hyperstart to exec a new workload
- Enable skipped docker exec tests
-Missing/wip:
*Add bats tests 
*Add unit tests 
*allocate a pseudo-TTY
*use newcontainer if exec is done before start
Fixes #18 #298

exec: Add support for runtime exec command

---

tests/integration/docker/run.bats

I had to include the "\r" in that string for things to work in the 2.0
era. It was a bit odd but I didn't question it too much then, the test
was doing what it was supposed to do: ensure the runtime doesn't output
anything on stdout/err.
2.1 fixes a few things with terminal handling, in particular we don't
have that spurious \r!

tests: Make testing for the run.bats output more robust

---

shim/shim.c

We currently set the terminal in raw mode. When we run standalone and pass $(tty) to --console option to start and stop a container, we would need to restore the terminal back.
After restoring the terminal, it does not behave as a raw terminal.

Restore terminal required for standalone case

---

tests/integration/docker/exit-code.bats
tests/integration/docker/terminal.bats

This PR contains two commits that add integration tests to verify exit codes and terminal setup:
integration tests: Add tests to verify that 
1. a pseudo tty is properly setup when it is requested
2. TERM environment variable is set when a tty is requested
3. TERM environment variable is not set when a tty is not requested
integration tests: Add test to verify exit code from a container
Add tests to verify that a container returns the correct exit code of the executed process.

Tests to verify exit codes and terminal setup

---

proxy/api/client.go
proxy/protocol.go
src/proxy.c
src/proxy.h

When passing the OOB fd data, we pass the dummy data ('F') and
that simplifies the message reading loop:
- When receiving a message, we no longer need to read the OOB data
at any point in time, but only at first.
- We only need to read actual data in the read loop, and there we
can handle EAGAIN more robustly: We retry as long as we don't
get the whole message length.
Fixes #508

proxy: Simplify fd passing and the message read loop

---

tests/process_test.c

This patch removes all references to STDIN_FILENO
in process_tests since if it is modified all
future tests will be affected causing bugs like #527
fixes #527

tests: Do not play with stdin in unit tests

---

Makefile.am
src/command.c
src/hypervisor.c
src/mount.c
src/oci-config.c
src/oci.c
src/oci.h
src/pod.c
src/pod.h
src/process.c
src/process.h
src/proxy.c
src/proxy.h
src/runtime.c
src/spec_handlers/annotations.c
src/state.c
tests/pod_test.c
tests/process_test.c

This pull request make Clear Containers work with the latest [CRI-O](https://github.com/kubernetes-incubator/cri-o) code.
CRI-O is a [Kubernetes CRI](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md) implementation for OCI compatible runtimes.
CRI-O only manages [Kubernetes pods](http://kubernetes.io/docs/user-guide/pods/) composed of 1 or more containers. In order to have COR embrace that concept, we add a pod structure to our config and state structures. This structure is also marshalled into our container state.json file.
```C
struct cc_pod {
/** If \c true, this is a sandbox container. */
gboolean sandbox;
/**
* The sandbox name holds the container ID for the
* sandbox container.
*/
gchar    *sandbox_name;
/**
* The sandbox …
```

CRI-O integration

---

src/commands/exec.c
src/oci.c
tests/pod_test.c

The CRI-O merge broke docker exec and introduced a test memory leak.
We only saw these issues when using cc-oci-runtime directly and not cc-oci-runtime.sh.
The console argument we receive is not NULL but empty (to signal us that we simply got `--console`) is set. So we need to check for the argument being non NULL and not empty to determine that we're using a terminal.
With the CRI-O merge we introduced a pointless config update that was breaking the interactive docker exec use case.
The `pod_test.c` tests were allocating a config pointer without releasing it. This is fixed as well.

Fix docker exec and test memory leak

---

tests/functional/version.bats

After release cc-oci-runtime 2.1-rc, version test started to fail. The
issue was caused because the test does not allow the string "2.1-rc"
as a valid version.
This patch modifies the version functional test to allow alphanumeric
values.

test: Fix version functional test

---

shim/shim.c

This makes it possible to handle all input in non-tty case.
Fixes #506.

shim: Handle stdin in non-tty case.

---

tests/integration/docker/run.bats

The stderr redirection docker test was being skipped. Unskip this and
add explicit checks to test the output before and after redirection.
Add the same verbose checking for  stdout redirection as well.

tests: Add explicit checking for stdout and stderr redirection tests.

---

src/oci.c
src/proxy.c
tests/oci_test.c

Support for CRI-O exec was broken:
- The config pod pointer is empty when calling exec on cc-oci-runtime. Therefore, we can not know which VM to attach to when being called from CRI-O
- CRI-O calls exec without a process.json file and thus we're giving hyperstart a process with an empty CWD to exec and that fails.
This PR fixes both issues.

CRI exec fixes

---

NEWS
configure.ac

- Added docker tests for handling pipe input
- Added pprof data export through HTTP
- Fixed CRI-O exec support
- Fixed shim atexit return value
- Fixed docker pipe inout handling (Issue #506)
- Fixed version functional test
Shortlog:
c22f33f proxy: Do not set the process CWD if it's empty
dbc634d oci: Build an accurate pod pointer before exec'ing
42acfd9 tests: Add explicit checking for stdout and stderr redirection tests.
a5a4f2d tests: Add docker test for handling stdin from pipe.
ba6e92d proxy: Add a way to serve pprof data over HTTP
80ceb96 shim: Add file descriptors at specifix index.
5d7ac88 shim: Handle stdin in non-tty case.
73e7d95 shim: atexit returns 0 if successful
baca26f test: Fix version functional test
6be54d4 tests: fix cc_oci_setup_shim test
Signed-off-by: Samuel Ortiz …

2.1.0-rc.3 release

---

tests/integration/docker/exec.bats

It seems the recent shim fixes make those tests run, at least they do
here!

tests: Enable the remaining docker exec tests

---

tests/helpers/test-campaign.sh

New option will let the user specify the directory where the
logs of the test execution will be saved.

Tests: Add option to specify LOG_DIR in test-campaign.sh

---

data/run-bats.sh.in

This commit makes functional tests to show its output in tap format
(ok and not ok) instead of using ✗ and ✓
This change will help to search for failures.

tests: show functional tests output in tap format

---

.ci/ci-build.sh
.ci/ci-go-static-checks.sh
.ci/ci-setup.sh
Makefile.am

Instead of waiting for travis to tell me I've done something wrong, fix
it and try my luck again with the other static tests, it'll be faster to
run them locally beforehand. To be used as:
Or

ci: Split go static checks so developers can invoke them

---

src/namespace.c
src/oci.c
src/process.c
tests/namespace_test.c

A new mount namespace MUST be created before mounting anything
since dockerd remounts container's filesystem when certain commands
are executed by docker causing issues like #325
fixes #325

namespaces: enable mount namespace

---

.ci/ci-go-static-checks.sh

We don't really have information on which test is running and which has failed. On top of that, the gofmt check was consuming stdout and so we were losing the list of guilty files failing the format check.
Running the checks now displays something like:
```
Doing go static checks on packages: ./proxy ./proxy/api
Running misspell...
Running go vet...
Running gofmt...
/home/damien/go/src/github.com/01org/cc-oci-runtime/proxy/fdleak_test.go
Makefile:5230: recipe for target 'check-go' failed
```

Better feedback when running go static checks

---

tests/integration/docker/swarm.bats

This will ensure that we are doing a ping with the non-empty replica
name

Test: Ensure that the name of a replica is not empty

---

Makefile.am
proxy/fdleak_test.go
proxy/proxy.go
proxy/proxy_test.go
proxy/vm.go

@devimc noticed a fd leak when killing the proxy savagely, it was due to the proxy never receiving the Bye payload.
Instead, the proxy now cleans up the per-VM resources when it detects the qemu process is gone.
I've added a generic "fd leak detector" that can help catch fd leaks and instrumented the proxy unit tests to check for those. A neat little thing that can be reused in other go projects:
https://github.com/dlespiau/cc-oci-runtime/blob/20170109-fd-leak-detector/proxy/fdleak_test.go
This leaves the case where the qemu process never goes away. It shouldn't happen, but we may want to improve our robustness with a mechanism killing qemu "after some time". It's not quite clear at this point if we should do that, it'd hide bugs and we'd have to decide where to put that mechanism (delete …

proxy fd leak & fd leak detector

---

tests/integration/docker/build.bats

Add initial bats test to verify "docker build"
compatibility.
Verifies support for #553 

test: Add "docker build" integration test

---

packages.json
vendor/github.com/containers/virtcontainers/README.md
vendor/github.com/containers/virtcontainers/hyperstart/hyperstart.go
vendor/github.com/containers/virtcontainers/hyperstart/mock/hyperstart.go

Let's vendor virtcontainers 0.2.3, it's a good version if we want to
minimize the changes while grabbing a fix for a panic that happens if
the shim disappears underneath us.
It's debatable if we should jump straight away to 0.3.0. That version
would also need us to re-vendor the runv package. It will have to
happen, eventually, but we can control when.
An benefit of going slowly on the updates is that we can revert a later
vendoring to 0.3.0 if we find out it introduces regressions.
Fixes: https://github.com/01org/cc-oci-runtime/issues/463

vendor: Revendor virtcontainers to 0.2.3 to fix a panic

---

proxy/proxy.go

We currently rely on a link-time option to specifiy the path of the proxy domain socket. We can provide a reasonable fallback in case the proxy is just compiled with "go build".

Support plain "go build" for the proxy

---

proxy/api/client.go
proxy/proxy_test.go

Those two proxy payloads will have some additional (optional) parameters, sometimes with the corresponding return values. In fact, we already have an optional parameter: the qemu console path that the runtime can provide to the proxy to display hyperstart messages.
So, we need a way to provide those optional parameters. This PR introduces the following pattern:
```
ret, err := client.Hello(containerID, ctlSocketPath, ioSocketPath,
&api.HelloOptions{
Console: "/path/to/qemu/console",
})
```
I could have introduced a HelloWithOptions that take that 3rd argument, but thought that might has well change it now while we can (unrelease API only used by unreleased tip of virtcontainers).
This will be used by followup PRs:
- The introduction of a version field in the Hello/Attach response
- The …

Futureproofing api.client.Hello and api.Client.Attach

---

Makefile.am
configure.ac

We had those components built and distributed in the 2.0.0 release but we weren't using them. Let's disable building and releasing them with the 2.0 runtime.
This should probably be followed with a 2.0.1 release.

Don't include neither the shim nor the proxy in the 2.0 branch

---

proxy/api/api.go
proxy/api/client.go
proxy/proxy.go
proxy/proxy_test.go

This PR adds a version field in the responses of Hello and Attach. See last commit for more details.
The 2 first commits are part of PR https://github.com/01org/cc-oci-runtime/pull/595 but included here as well as dependencies.

Version the proxy protocol

---

NEWS
configure.ac

2.0.1:
Disable the cc-shim and cc-proxy build
Shortlog:
57cedac Merge pull request #603 from dlespiau/20170120-2.0-no-shim-no-proxy
f1e5a61 build: Don't compile the shim
28e3ca6 build: Don't distribute the proxy files
f5fdf5f build: Don't require go anymore
6851b65 build: Don't compile the proxy
472a06a build: Update the version in configure.ac to 2.0.0

configure: Move to 2.0.1

---

src/semver.c
src/semver.h
tests/semver_test.c

This patch removes cc_oci_semver_cmp_full
to make cppcheck happy again

cppcheck: fix cppcheck errors

---

.ci/ci-go-static-checks.sh

The readme of that tool is a bit terse "Detect ineffectual assignments
in Go code." but this is useful to catch improper assigments of errors
(for instance).
This test is also part of goreport (https://goreportcard.com/) so it's a
good idea to include it and be good go citizens:
https://goreportcard.com/report/github.com/01org/cc-oci-runtime

ci: Add ineffassign to the go static checks

---

src/main.c

This patch verify if the system supports virtualization
reporting an issue when it has not support
fixes #596

runtime: verify if the system supports virtualization

---

Makefile.am

This package has been moved to virtcontainers and this variable wasn't
defined anywhere anymore.

build: Remove the last reference to the hyperstart mock package

---

src/oci.c
src/process.c

Docker introduced the change to attach stdio streams before create
with this change : https://github.com/docker/docker/pull/26744.
Before this change, the streams were attached after the post-start hooks
were executed.
This caused the shim to read stdin and send it to hyperstart before
the container was started, causing the input to be dropped.
So, put the shim in paused state after create and have the runtime
start it only after the container has been started.
Fixes #566.

start: Delay shim execution until start has been called for runtime.

---

proxy/api/client.go
proxy/protocol.go
src/proxy.c

In:
commit 50d42dc434f283ccb6e5daa17ea98d376b86fc4c
Author: Samuel Ortiz <sameo@linux.intel.com>
Date:   Mon Dec 19 15:00:25 2016 +0100
proxy: Simplify fd passing and the message read loop
Samuel changed the order to send the fd before the response and simplify
the reading loop.
In this commit, I put it back the other way: response, then fd. It
allows for a more natural checking of the response status before trying
to receive the fd. If the allocateIO fails, we don't even try to read a
fd from the proxy.
That change is motivated by another one: we now have a
cc_proxy_receive_fd() function that is orthogonal to reading the
response back from the proxy. That means we can use it several times in
a row to retrieve more than one fd, a useful feature we'd like to use
very soon.
Signed-off-by: …

proxy: Reorder response and fd

---

src/mount.c
src/namespace.c
src/namespace.h
src/oci.c
src/oci.h
src/state.c
tests/mount_test.c

support for mount namespace was add in PR #577 to fix #325
all resources mounted by the runtime are part of a new
mount namespace hence when delete is called the runtime is
unable to unmount them. This patch fixes that issue joining
to the namespace and unmounting all resources
fixes #593

 mount: fix umount function

---

proxy/protocol.go

When failing to send a fd to the client, we were forgetting to close the
fd we were trying to send.

proxy: Fix a fd leak in an error path

---

DESIGN.rst

This whole section is out of date. I'm not a big fan of documenting this
level of details in an external document, it's bound to get of date
creating more work than necessary. We should have an adequate amount of
comments embedded in the code instead.

docs: Remove the section about starting the hypervisor

---

NEWS
configure.ac

2.1.0.rc.5:
Added SELinux configuration for proxy
Added environment and image docker tests
Added virtualization support check
Added ineffassign CI tests
Added proxy protocol extensions
Fixed a potential proxy panic
Fixed umount function
Fixed support for latest Docker streams
Fixed a proxy fd leak
Shortlog:
754877f selinux: Initial commit for cc-proxy selinux module
e5a7837 docs: Remove the section about starting the hypervisor
013b0a9 docs: Add a section about contributing to Go code
0b681a8 docs: Update the coding style section
4428e60 docs: Add proxy and shim to the Code layout section
4f49acb mount: fix umount function
7eb940c runtime: add namespace to oci_state struct
e376fb6 runtime: refactor namespace file
b683f66 tests: Unskip environment test as issue #324 has been resolved. …

configure: Move to 2.1.0-rc.5

---

Makefile.am
tests/functional/run-functional-tests.sh.in

This patch replaces builddir and abs_top_srcdir with abs_builddir
to run cc-proxy and cc-shim since these binaries are placed
in that directory(abs_builddir) when they are compiled
Errors fixed:
* ../cc-oci-runtime-2.1.0-rc.4/_build/sub/../../cc-proxy: No such file or directory
* ../tests/functional/run_functional_tests.sh: line 9: kill: (7575) - No such process

tests: Fix distcheck errors

---

tests/integration/docker/attach.bats
tests/integration/docker/commit.bats
tests/integration/docker/cp.bats
tests/integration/docker/create.bats
tests/integration/docker/env.bats
tests/integration/docker/exec.bats
tests/integration/docker/exit-code.bats
tests/integration/docker/export.bats
tests/integration/docker/info.bats
tests/integration/docker/inspect.bats
tests/integration/docker/kill.bats
tests/integration/docker/load.bats
tests/integration/docker/logs.bats
tests/integration/docker/network.bats
tests/integration/docker/port.bats
tests/integration/docker/restart.bats
tests/integration/docker/run.bats
tests/integration/docker/swarm.bats
tests/integration/docker/tag.bats
tests/integration/docker/terminal.bats
tests/integration/docker/user.bats
tests/integration/docker/volume.bats
tests/lib/test-common.bash

Before this patch some containers were not deleted in the test
where them were created causing random failures into the next tests
With this patch all container will be deleted where them were created
The main issue was this line:
```
"$DOCKER_EXE" ps -q | xargs -r "$DOCKER_EXE" kill
```
for example:
One container called 'tequila' is running.
When ```"$DOCKER_EXE" ps -q``` is executed the word 'tequila' is returned
but immediately 'tequila' dies ;( .
When ```xarg -r "$DOCKER_EXE" kill``` is executed docker tries
to kill to 'tequila' but it is already dead causing issue #593
"""Error response from daemon: Cannot kill container 'tequila'"""
RIP 'tequila'
fixes #593

tests: fix docker functional tests

---

proxy/vm.go

I placed the signal that we've lost the VM when the read() on the I/O
socket was failing. That was missing the rest of hyper to client I/O
copy loop: there are other places where having lost the VM will result
in this goroutine returning.
So, instead, place the VM lost signal at the end of the goroutine, we'll
signal we've lost the VM in all circumstances that way.
Fixes: https://github.com/01org/cc-oci-runtime/issues/622

proxy: Fix the VM lost detection site

---

proxy/vm.go

Looking at coverage pointed out that this method may not be used
anywhere and indeed it wasn't.

proxy: Remove unused vm.CloseIO() method

---

src/process.c
src/util.h
tests/process_test.c

This PR simplifies the way we spawn hooks.
Currently hooks that do not read the container
state from stdin, and/or ends before cc-oci-runtime
sends the container state through stdin will fail.
fixes #632

Fix invalid file descriptor

---

proxy/vm.go

That's a bug we have had for the longest time. There is one such
goroutine per VM and we where quitting it whenever we had an error
writing data to a shim.
However, we may have a number of shim per-VM, one for the initial
container and one for each exec. We can't just quite the whole goroutine
if the write to one of the shim is failing.
This bug was discovered because we know signal "VM lost" when this
goroutine exits, which was causing havoc.
Fixes: https://github.com/01org/cc-oci-runtime/issues/638

proxy: Don't quit the hyper->client IO goroutine when a shim dies

---

tests/integration/docker/info.bats

Since:
commit c8b933adb193d611fc0998368f866d8028efe99a
Author: Julio Montes <julio.montes@intel.com>
Date:   Thu Jan 26 18:16:44 2017 -0600
tests: fix docker functional tests
We don't run docker rm in setup(), which is a good thing and avoid hiding bugs.
However it's possible the system we are running on still has some
(stopped) containers not yet deleted. It's slightly more robust to use
the number of running containers for the check we do here.

tests: Use the number of running tests in info.bats

---

tests/metrics/density/docker_cpu_usage.sh.in
tests/metrics/density/docker_memory_usage.sh.in
tests/metrics/workload_time/cor_create_time.sh.in
tests/metrics/workload_time/docker_shutdown.sh
tests/metrics/workload_time/docker_workload_time.sh
tests/metrics/workload_time/kernel_boot_time.sh

With this patch metrics tests will use random names
to run and delete containers
fixes #652

tests: fix tests that depend of clean_docker_ps

---

tests/integration/docker/swarm.bats

This PR fixes:
- replicas obtained from non-running containers:
The swarm tests are verifying the interfaces and IP addresses
from the containers listed with 'docker ps -a -q', but this fails
if there is a container that is not running (which maybe was created
before running the tests).
This commit changes the command to 'docker ps -q' so that we only
get the list of containers that are running.
- a typo in swarm.bats
- indentation issues.

Swarm tests fixes 

---

tests/metrics/README.md
tests/metrics/collect_mem_consmd.sh

This tool allows to measure the average memory
consumption of a Clear Containers component during
a determined Clear Containers stress test.
The parameters that modify the stress level are:
* number of clear containers.
* workload for all instances.
can be customized.
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>

Add memory consumption tool

---

NEWS
configure.ac

2.1.0-rc.6:
Added additional groups and user related tests
Added docker attach functional tests
Added back popular containers tests
Added memory consumption tool
Fixed invalid file descriptor Glib warning
Fixed removing stale docker instances after docker rm
Fixed distcheck, functional and unit tests
Shortlog:
e456fb1 Add memory consumption tool
e6d9e53 Update Clear Containter image version
02ae0b6 tests: fix tests that depend of clean_docker_ps
d953ce6 tests: Swarm - get replicas only from active containers
6fa06df tests - Fix 'attemps' typo and indentation issues in swarm.bats
e29f844 ci: Send Travis notifications to Slack
15f7f18 tests: Tighten the docker info check
a1682cd proxy: Don't quit the hyper->client IO goroutine when a shim dies
5f35b14 Test: Delete function from the setup …

configure: Move to 2.1.0-rc.6

---

.ci/ci-build.sh
.ci/ci-configure.sh
.travis.yml

The existing ./autogen.sh call was missing many of the exported
variables from ci-common.sh and was for example not finding our
locally installed glib.
This patch extracts the configuration part from ci-build.sh into
ci-configure.sh and call the latter as the coverity prepend build.
Fixes #533

ci: Run complete configuration to prepare coverity build

---

NEWS
configure.ac

2.1.0:
Fixed coverity token
Add complete configuration to prepare coverity build
Shortlog:
cf0e726 ci: Run complete configuration to prepare coverity build
c82fe5e ci: Fix coverity token

release: version 2.1.0

---

.ci/ci-setup.sh

The travis builds started failing with errors when installing packages.
Turns out we need to do an apt-get update before install when using the
standard infrastructure:
https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Standard-Infrastructure

build: Run apt-get update before installing packages

---

Makefile.am

The code introduced to test if -race is supported on commit
19c45031ddf04240bbbb9748cbb35e100c22ef3f was not working.
Ubuntu OBS builds fails at that point after detecting an error.
With this simple fix, the build will try to test cc-proxy with -race
enabled and if it fails it will try another time without -race.
Fixes #670
Tested on OBS builds.

Build: Fix -race pre-test to test cc-proxy

---

documentation/Installing-Clear-Containers-on-Centos-7.md
documentation/Installing-Clear-Containers-on-ClearLinux.md

This commit adds instructions on how to install and run
Clear Containers 2.1 on Clear Linux and Centos 7.

docs: Add Clear Linux and Centos 7 installation instructions

---

src/process.c

When "create" fails, we forcefully kill the shim with SIGKILL.
The vm may still be around at this point, kill the vm as well.

create: Kill the VM along with shim on create error.

---

proxy/fdleak_test.go

*Note: This bug was discovered in clearcontainers/proxy when testing against go tip (what will become 1.9). It's a real bug though that could have happened even with earlier go versions.*
When we've already failed the comparison for a previous fd, nothing
should be able to make us return true.
Unfortunately, we were overriding unconditionally the equal boolean
with no regard of the past.
This was found testing the proxy on go tip (what will become 1.9), the
runtime has changed and exposed that bug.

fdleak: Don't let Compare() return true when it shouldn't

---

src/command.c
src/oci-config.c
src/oci.h
src/process.c
src/spec_handlers/linux.c
tests/data/linux-no-cgroupsPath.json
tests/data/linux.json
tests/spec_handlers/linux_test.c

Docker provides a cgroup path where the workload MUST be
added before create pid file otherwise docker will create a new
cgroup and add the workload to it.
When workload process ends the runtime MUST delete the cgroup path
notifying docker to free its open event file descriptors otherwise
docker won't close them causing file descriptors leaks.
fixes #616

runtime: Fix docker file descriptor leaks

---

Makefile.am

Previously, the documentation was distributed in
"documentation/documentation/", rather than just "documentation/".

docs: Fix distribution of documentation.

---

Makefile.am
data/genfile.sh
tests/metrics/run_docker_metrics

This patch adds a new script to process .in files
run_docker_metrics uses this script to generate
its dependecies if they do not exist
fixes #369

tests: fix run_docker_metrics script

---

src/commands/kill.c
src/oci.c
src/oci.h
src/proxy.c
src/proxy.h
src/util.c
src/util.h
tests/functional/kill.bats
tests/oci_test.c
tests/util_test.c

With this patch users will can send signal to
all processes running inside the container
fixes #693

runtime: add --all option to kill command

---

Makefile.am
configure.ac

We need to set GOPATH variable if it not previously defined.
This aims make easier to build cc-oci-runtime in different distros.

packaging: Add option to set GOPATH (packaging, tests, automated builds)

---

Makefile.am
tests/integration/docker/attach.bats
tests/integration/docker/build.bats
tests/integration/docker/commit.bats
tests/integration/docker/cp.bats
tests/integration/docker/create.bats
tests/integration/docker/env.bats
tests/integration/docker/exec.bats
tests/integration/docker/exit-code.bats
tests/integration/docker/export.bats
tests/integration/docker/info.bats
tests/integration/docker/inspect.bats
tests/integration/docker/kill.bats
tests/integration/docker/load.bats
tests/integration/docker/logs.bats
tests/integration/docker/network.bats
tests/integration/docker/port.bats
tests/integration/docker/restart.bats
tests/integration/docker/run.bats
tests/integration/docker/swarm.bats
tests/integration/docker/tag.bats
tests/integration/docker/terminal.bats
tests/integration/docker/user.bats
tests/integration/docker/volume.bats
tests/lib/test-common.bash.in

This commit enhances the tests to verify that the
containers and all subprocesses (cc-shim and qemu)
are killed properly.
Fixes #647

tests: fail tests if a process is left behind

---

.pullapprove.yml

There is now a new 'on-hold' tag which is similar to 'do-not-merge' and
'wip'. Unlike the latter two tags (which are generally added by the author),
the intent is for 'on-hold' to be added to a PR by a reviewer to
signify that the author needs to either make further changes or respond
to review feedback. This new tag makes it easier to identify such
"in progress" PRs when reviewing the PR backlog and since they are not
complete PRs with this tag should not be approvable.

CI: Disallow approval of 'on-hold' PRs

---

src/commands/kill.c
src/oci.c
src/oci.h
src/proxy.c
src/proxy.h
src/util.c
src/util.h
tests/functional/kill.bats
tests/oci_test.c
tests/util_test.c

hyperstart 0.7.0 has not support to kill all processes inside
the container so 61e511eaee17caec904372aebfb7dc87aa3d6840 is
causing issues killing containers.
This reverts commit 61e511eaee17caec904372aebfb7dc87aa3d6840.

Revert "runtime: add --all option to kill command"

---

configure.ac

2.1.1:
Added installation instructions for Ubuntu
Added small history section covering V2.0 and V1.0
Added DAX appendix to architecture documentation
Added MTU support for network interface
Fixed docker file descriptor leaks
Fixed additionalGids array assignment
Added Clear Linux and Centos 7 installation instructions
Added Clear Containers architecture
Shortlog:
c228baa Documentation: Add installation instructions for Ubuntu
5b179b0 tests: fix run_docker_metrics script
ebff893 CI: Disallow approval of 'on-hold' PRs
4bae2a9 packaging: Adds --enable-autogopath, default=false
ed6c49c docs: Fix distribution of documentation.
d7552f3 docs: Add small history section covering V2.0 and V1.0
74aab81 docs: Add DAX appendix to architecture documentation
5e741b0 tests: fail tests if a process is …

release: version 2.1.1

---

Makefile.am

removes genfile.sh from /usr/share/defaults/cc-oci-runtime/
genfile.sh MUST NOT be installed

dist: moves genfile.sh to extra dist

---

README.rst

Currently the qemu-lite link points to master branch which does not have
the pc-lite machine type.
This commit makes clear to the user they need to use qmeu-2.7-lite branch.

doc: Update qemu-lite link

---

src/mount.c
src/mount.h
src/oci-config.c
src/oci.c
src/oci.h
src/pod.c
src/process.c
src/proxy.c
src/state.c
tests/oci_test.c

This PR carries a couple of CRI-O/k8s related fixes for 2.1.1:
1. Do not force hyperstart into creating users for a pod (This is preventing CRI-O pods to be created at all).
2. Create pod and pod containers cgroups.

CRI-O fixes for 2.1.2

---

documentation/Quickstart-Clear-Containers-in-a-Ubuntu-VM.md

ciao-down allows for a simple eval, dev and test environment to
try out clear containers. This document calls out how to use
ciao-down with clear containers.

Documentation: ciao-down support for clear containers

---

.ci/ci-go-static-checks.sh
Makefile.am

The vendor/ directory needs to be added to the distribution archive to
allow the package to be built fully from that archive.

Build: Distribute vendor directory.

---

tests/integration/docker/dns.bats

Addition of the functions check_no_processes_up and
kill_processes_before_start to the DNS test

Test: Add new functions to DNS test

---

tests/functional/run-functional-tests.sh.in

This commit makes `make functional-tests` return an
exit code different from zero if one or more tests fail.

tests: return exit code diff from zero if a test fail

---

src/mount.c

We only want to fail if our config is NULL. The list of OCI mounts being
empty is a perfectly valid use case.

mount: Remove bogus parameter check

---

Makefile.am

Otherwise 'make docker-tests' breaks.
Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>

tests: generate test-common.bash for docker-tests

---

tests/integration/docker/dns.bats
tests/integration/docker/swarm.bats

Deleting function clean_swarm_status from the script as this
is already part of the test-common.bash

Tests: Delete function clean_swarm_status

---

.pullapprove.yml

Now that we have rcaballeromx as documentation owner,
I am adding him as a reviewer for changes in the files
inside docs directory and for any md and rst file.

docs: add reviewer for documentation on pullapprove

---

tests/metrics/collect_mem_consmd.sh
tests/metrics/smem_monitor.sh

This script will show an average about RSS memory
and PSS memory. RSS memory is measured by collectl
tool and PSS memory by psstop tool.
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>

tests/metrics: Add support to measure RSS and PSS

---

documentation/Installing-Clear-Containers-on-Ubuntu.md

A here-document is terminated by the token immediately after "<<",
not "token >>".

docs: Remove erroneous here-document syntax from Ubuntu install guide.

---

documentation/Installing-Clear-Containers-on-Ubuntu.md

The Ubuntu installation guide was using the lsb_release(1) command to
simplify adding the docker apt repository. However, lsb_release(1) can only
be used for Ubuntu 16.04 (xenial) - the commands will fail when running
on Ubuntu 16.10 (yakkety) since docker does not provide version 1.12.1
for yakkety and we only currently support docker 1.12.1.

docs: Remove use of lsb_release(1) for docker in Ubuntu install guide.

---

documentation/Installing-Clear-Containers-on-Fedora-25.md

The '#' tags for headings in the Fedora install instructions
were incorrectly formatted, not having a ' ' folling the '#',
and thus did not render (on github at least).
Fix by adding the ' 's in.

docs: Fedora Install: Fix headings tags

---

.ci/ci-go-static-checks.sh

We run gofmt with the simplify (-s) flag. Some of the rewrite rules are
hidden behind that flag because they break previous go versions. Editors
don't run gofmt with -s by default for that reason and so it's not
unlikely the static checks scripts find something to change.
We can do better than displaying the list of "offending" files, we can
make gofmt display the unified diff with the suggested simplification.
It's just a matter of using the -d flag.

ci: Display unified diff with what gofmt wants us to change

---

src/oci.c

This patch is to avoid failures when cor tries to
stop cc-shim when it was already stopped

runtime: check if cc-shim is running before stop it

---

proxy/README.md

I needed a sudo on the journalctl command to access the logs, so
add it in - given we are showing a sudo needed for systemctl as well.

proxy: README: Add sudo to journalctl command

---

README.rst

As we now have golang code in the tree, you must have the repo/code
in your GOPATH, or it won't build. Add that info to the Building
section.
Fixes: #749 

Docs: README: Add GOPATH requirement to source location

---

src/mount.c

The pod sandbox container is just a regular container and should be
treated as such, otherwise all its OCI mount paths are incorrect.

mount: Fix mount path for pod sandbox containers

---

src/mount.c
src/oci.c
src/pod.c
src/pod.h
src/proxy.c
tests/oci_test.c
tests/pod_test.c

cc-oci-runtime list would always return `stopped` for pod containers.
Pod containers are shim controlled containers, but they're not associated to a VM, so `cc_oci_vm_running` would always return false on them.
This PR generalizes `cc_oci_vm_running` to `cc_oci_container_running` and consider both VM linked containers (Docker containers and pod sandbox containers) as well as pod containers.

Fix cc-oci-runtime list for pod containers

---

tests/lib/test-common.bash.in

running 'docker ps -q' with double quotes result in an error:
command not found. This commit fixes the call of that command.

tests: fix setup command that kills running containers

---

Makefile.am

Adding the -fPIE -pie flags in order to harden the security. It creates our binary as a Position Independant Executable, and takes advantage of ASLR, making ROP attacks much harder to perform.
See https://wiki.debian.org/Hardening for further details.

Makefile: Add build hardening with -fPIE flag

---

configure.ac

In order to harden the build and the overall security of the project, this patch enables FORTIFY_SOURCE optimization in case the flag --enable-debug is not detected.
Indeed, when debug is enabled, the -O flag is set to -O0, and the option FORTIFY_SOURCE expect at least -O1 to be properly enabled.

configure.ac: Add -D_FORTIFY_SOURCE=2 optimization

---

.ci/ci-setup.sh
Makefile.am
configure.ac
data/genfile.sh
tests/data/container_redis.json
tests/data/policy.json
tests/data/sandbox_config.json
tests/integration/README.md
tests/integration/cri-o/container.bats
tests/lib/test-crio.bats.in

Through `make crio-tests`, we add CRI-O integration tests. This needs to be configured in with a new `--enable-crio-tests` configure option.
For now, we only have one test that starts a pod and a redis container within that pod and verifies that they're both running fine. Then it stops both container and pod.
This will give us a quick BAT for CRI-O support.
Fixes #723

CRI-O integration tests

---

Makefile.am

As we want to increase the security of the project, we want to make sure we have both noexecstack and relro flags enabled. By default on several distributions, gcc will enable those flags, but we don't want to end up with a case where those flags are not enabled.
About the details of these flags, noexecstack protects the stack from being executed, while relro protects against data relocation.

Makefile: Ensure noexecstack and relro are enabled

---

src/commands/exec.c

Probably just a copy/paste effect in action. runc abbreviates --tty
with -t as well.

exec: Short option for --tty should be -t

---

configure.ac

2.1.2:
Enabled noexecstack and relro
Added -D_FORTIFY_SOURCE=2 optimization
Fixed runtime list for pod containers
Added a pod container check
Added script to install clear container in RHEL
Added CRI-O integration tests
Fixed mac address for configuring network interface
Updated image version to get latest hyperstart changes
Added scalability tests
Added tool for memory mapping
Fixed intra pod containers volume support
Honoured detach option in exec command
Add version details to log file
Added --all option to kill command
Added fedora installation details
Added RHEL installation details
Added support to measure RSS and PSS
Added MTU tests using swarm
Added ciao-down documentation for clear containers
Added cgroup file creation test
Created cgroups for pods and containers
Shortlog: …

release: version 2.1.2

---

installation/rhel-setup.sh

The last two commands in rhel-setup.sh must be run as root so require
the use of sudo(8) for consistency with the rest of the script.

install: Fix Clear Containers Docker config generation.

---

tests/metrics/network/network-metrics.sh

This script will measure network bandwidth, jitter, network bandwidth
for multiple TCP connections, UDP network bandwidth and bi-directional
network bandwidth using iperf in a local setup (1 client - 1 server in
the same hardware).

Metrics: Network Measurement using Iperf

---

.ci/ci-configure.sh
Makefile.am

When there is something wrong running the cri-o tests, some cri-o
processes get hanged and the test does not finish, this affects the
CI.
Normally, the test takes around 2 minutes to be executed succesfully,
so this commit adds a timeout of 4 minutes to complete the cri-o test.

tests - add timeout for cri-o tests

---

tests/metrics/density/docker_memory_usage.sh.in

The CC memory footprint calculation will
be got according to following Eq[1] instead to
just measure qemu instances.
[1] CC-mem=avg(PSS all qemu) + avg(PSS all cc-shim) + (PSS cc-proxy / N)
Where N is the number of containers.
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>

metrics: Fix CC memory footprint calculation

---

Makefile.am
configure.ac
data/cc-bootchart.conf
documentation/Get-Bootchart-metrics.md

This patch add a new config file for systemd-bootchart in the clear container image.
The config file can be installed in the clear container image rootfs
using the  configure option:
--with-cc-image-bootchart-config-dir=DIR
The config will tell systemd-bootchart to generate the
svg image in the container rootfs.
This will allow get a boot chart from a container when the systemd-bootchart is used as init (init can
be changed in the kernel cmdline in the vm.json file )
docker run --rm -ti debian bash -c 'sleep 10s; cat /run/*.svg' > ./bootchart.svg

metrics: Add cc-bootchart.conf

---

configure.ac

2.1.3:
Fixed compatibility with docker v17.03.1-ce
Added iperf tests to measure network
Shortlog:
a68d318 metrics: Add cc-bootchart.conf
eb1dfd0 tests/metrics: networking. fixup double space in iperf3 script
6cf02dc tests/metrics: networking, iperf3 tests - describe functions
f2bfa1a tests/metrics: networking. iperf3. Combine identical client/server test
d1b5f13 runtime: remove unused state
3972250 runtime: delete command must terminate the VM
09e48fc runtime: Add validation to avoid any possibility of an overrun
bfe3196 tests: do not fail if pid file does not exist
af1d8e2 tests: fix test according to new kill workflow
0e69d1f runtime: add -w option to cc-shim
635b545 runtime: redesign kill command workflow
f303930 shim: Add new option to kill the VM when shim is the initial workload …

release: version 2.1.3

---

tests/integration/docker/kill.bats

this tests kills a container with a no termination signal
and then checks its exit code

tests: kill a container with a no termination signal

---

proxy/cc-proxy.socket.in

We don't need those sockets to be read/writable to the whole world. Only
root is enough.

proxy: Restrict the socket and parent directory modes

---

proxy/fdleak_test.go

When a test fails, we may not generate a fd snapshot and end up in
Compare with nil snapshot(s).
Compare() should handle that case gracefully instead of generating a
panic.

fdleak: Handle nil snapshots in Compare

---

configure.ac

2.1.4
Fixed cc-proxy socket and parent directory modes
Shortlog:
841d8e7 docs: update clear containers image version
00f182b fdleak: Handle nil snapshots in Compare
80426a5 Metrics: Improve readability for iperf2 metrics
3338dc8 proxy: Restrict the socket and parent directory modes
138c09f Metrics: Improve readability
899bb76 tests: kill a container with a no termination signal

release: version 2.1.4

---

proxy/README.md

The opening ( has to be just after ] or the md parser doesn't understand
this is a [label](url) construct.

README: Fix URL markup

---

Makefile.am
configure.ac
tests/metrics/README.md
tests/metrics/run_docker_metrics

This PR contains 3 commits:
- metrics - Add Makefile rule to run metrics tests
This new Makefile rule will run all metrics tests in
tests/metrics/run_docker_metrics and will generate the files
needed to execute them
- metrics doc - update metrics README
This change documents how to execute the new rule to
execute the metrics tests.
- metrics - abort metrcis tests if generated files are missing
This commit will verify if the test/lib/test-common.bash is
already generated before running the metrics tests. It will
also tell you to use the Makefile rule 'make metrics-test' so
the missing files are generated.

Add 'make metrics-tests' rule to execute all metrics

---

src/oci.h
src/proxy.c
src/spec_handlers/process.c
tests/data/process-invalid-relative-cwd.json
tests/data/process-no-args-cwd.json
tests/data/process-no-consolesize.json
tests/data/process-no-cwd.json
tests/data/process.json
tests/functional/data/config-minimal-cc-oci.json.in
tests/spec_handlers/process_test.c

console size can be specified in config.json this patch
add support to handle this case and change console size
when container is launched
Fixes #690

oci: add support for OCI 1.0.0-rc5

---

configure.ac

2.1.5:
Fixed failure when trying to create a pod #815
Added network test using nginx and ab
Added support for OCI Runtime Specification 1.0.0-rc5
Fixed failure obtaining host name of a replica in Swarm #578
Added installation script for RHEL and CentOS
Shortlog:
11d81fb networking: Disable udev from assigning predictable interface names
27284c8 Metrics: Network test using nginx and ab
4e133fe version: Update kernel to version 4.5-57
70fc5d4 version: Update container image version to 14700
32a5f18 tests: add json file to test process without consoleSize
e8cc984 networking: Skip sending iptable rules to hyperstart while running tests
047fd21 tests: Unskip test to obtain hostname of a replica in Swarm
b46f03f networking: Send the iptable rules to hyperstart.
7b13aaa networking: Save and …

release: version 2.1.5

---

documentation/Installing-Clear-Containers-on-Ubuntu.md

Fix (redundant) double sudo(8) call in Ubuntu install guide.

docs: Remove duplicate call to sudo(8).

---

tests/metrics/network/network-metrics-nuttcp.sh

UDP network bandwidth using nuttcp with two different
buffer sizes

Metrics: UDP Network Bandwidth

---

README.rst
configure.ac
versions.txt

version 2017.03.21 of autoconf-archive is required
because this version contains a macro (AX_VALGRIND_DFLT)
to enable or disable valgrind tests

versions: Specifies a version of autoconf-archive

---

CONTRIBUTING.md

Fix hotlink format in CONTRIBUTING file so it renders properly on github.
Fixes #857

docs: contrib: Fix hotlinks in contributing document

---

CONTRIBUTING.md

Previously adding a "Fixes #XXX" commit message was optional, but we
have found that "stale" issues are being left open. Require such a
comment to have those issues automatically closed.

docs: Require every PR to include a "Fixes #XXX" comment.

---

configure.ac

- Fixed: docker: Error response from daemon: shim error: open pid: no such file
or directory on Centos #850
- Fixed: hyperstart failures when running cc-oci-runtime on Ubuntu #837
- Metrics: CPU % consumption for network
- Updated kernel version to 4.9.24-60
Short log:
11bedb3 docs: Require every PR to include a "Fixes #XXX" comment.
aa3f234 docs: contrib: Fix hotlinks in contributing document
a210cc4 versions: Specifies a version of autoconf-archive
b67f0f7 Metrics: CPU % consumption for network
06a5340 version: Update versions of linux kernel and qemu-lite
d1fd072 tests: Adds new target to run valgrind tests
4c8cb61 ci: Download code coverage and valgrind m4 files
ae8ac0a autogen: create m4 directory before autoreconf
b8691c5 installation: Download m4 files archives in RHEL
3be9a9c …

release: version 2.1.6

---

src/netlink.c

This may possibly resolve #581. Multicast snooping may be
turned on the bridge depending on the distro kernel config.
Disable this explicitly.

networking: Disable multicast snooping on the bridge we create

---

Makefile.am
tests/metrics/network/network-metrics-memory-pss.sh.in

Measure Proportional Set Size Memory using smem while
running a bandwidth measurement using iperf2

Metrics: Measure PSS memory while running network

---

.ci/ci-pre-checks.sh
.travis.yml

The script is called before the CI runs any setup/build/tests and
performs the following checks on all commits:
- Subject
- Contains a subsystem.
- Length is within prescribed limits.
- Body
- Contains a "Fixes #XXX" comment.
- Line lengths are within prescribed limits.
Fixes #872.

CI: Add script to perform basic checks on commits.

---

configure.ac

- Added shim debug logs when runtime debug option is used #878
- Fixed Kernel panic using swarm #581
- Added Metrics to measure memory running network test #865
9911475 shim: Do not print to stderr as well while logging
95369ca logging: When invoked with debug flag, pass that to the shim
539b082 CI: Add script to perform basic checks on commits.
9c92a15 Metrics: Remove iperf2 tests
001e264 networking: Disable multicast snooping on the bridge we create
ab3d6e4 Metrics: Measure PSS memory while running network
Fixes #881
Signed-off-by: Carlos Venegas <jose.carlos.venegas.munoz@intel.com>

release: 2.1.7

---

configure.ac
data/hypervisor.args.in
documentation/Using-OVS-DPDK-and-COR.md
documentation/Using-VPP-and-COR.md
src/hypervisor.c
src/networking.c
src/networking.h
src/oci.h

PR to enable VPP for POC work on 01org/cc-oci-runtime's network/vhost-user-poc branch.
OVS plugin should be updated to make use of this branch instead of OVS-DPDK POC going forward.
Verified with latest cc-oci-runtime released, 2.1.4.

Vhostuser network enabling

---

documentation/Installing-Clear-Containers-on-Fedora-25.md

A hotlink was using '[] ()', where the inter-bracket space breaks
markdown rendering of the hotlink on github at least. Fix it (remove
the space).
Fixes #857 (issue is referenced in that ticket)

docs: Install: Fedora: Fix broken markdown hotlink

---

tests/metrics/density/docker_memory_usage.sh.in

If the docker memory PSS footprint test failed to find the PSS
figures for any of the components (qemu, shim, proxy), then it
would return '0' internally, and still generage a results file,
with incorrect results.
Improve the robustness of the script by trapping any '0' results
where they are not expected.
Reasons smem may fail to find the PSS of a process include:
- the process name may have changed
- the process may not be running (may have died for instance)
- the test is not run with enough priv to read the smaps for the
process
Fixes: #879

tests: metrics: Improve robustness of PSS mem footprint test

---

configure.ac

befe20e docs: Install: Fedora: Fix broken markdown hotlin
53ff98c Metrics: Latency measurement
066568e tests: metrics: Improve robustness of PSS mem footprint test
Fixes #899 

release: 2.1.8

---

src/netlink.c

Added definition for IFLA_BR_MCAST_SNOOPING. This enum will
not be present in older kernels and there isnt a way to detect
its support at preprocessor time.
Fixes #893

networking: Fix compilation issue on Centos.

---

tests/metrics/network/dockerfile_image/Dockerfile
tests/metrics/network/dockerfile_image/README.md

Add Dockerfile to create the network image currently used in all our networking testing. This Dockerfile will install all the dependencies that are required.
Add a README where it has the basic steps of building the image and verifying the image.

Add Dockerfile and README for network images

---

src/netlink.c

Get rid of undef and rely on the definition we provide
for muticast snooping. This was an oversight in realizing that
the undef happens unconditionally at compile time.

networking: Fix compile for bridge networking code

---

documentation/Installing-Clear-Containers-on-Centos-7.md
documentation/Installing-Clear-Containers-on-Fedora.md
documentation/Installing-Clear-Containers-on-Ubuntu.md

This commit adds instructions on how to install Docker 17
It also specifies to the user that Swarm only works with
Docker 1.12.1.

docs: Update instructions to install latest Docker

---

.ci/ci-configure.sh
Makefile.am
README.rst
autogen.sh
configure.ac
versions.txt

Asking for a recent autoconf-archive makes it extra difficult  to build cc-oci-runtime in older distros: Ubuntu 16.04, Ubuntu 16.10 Fedora 24.
With this patch I am removing the requeriment for a recent autoconf-archive as well as references to AX_VALGRIND_DFLT.
Added --disable-valgrind-sgcheck to default build options
Fixes #888 and #887

build: remove requeriment to have a recent autoconf-archive

---

proxy/api/protocol.go

Issue detected with vetshadow. Rename the variable to avoid
shadowing the type.

proxy: Avoid shadowing type "header" with variable "header"

---

tests/integration/docker/user.bats

The test 'Running with additional groups' uses busybox image
which previously used id 99 for nogroup. In its latest
update, busybox now uses id 65534 as other distros do.
The test now uses a regex for verifying this id.

tests: updated user.bats to check group id with a regex

---

data/obs-packaging/cc-oci-runtime/README.md
data/obs-packaging/cc-oci-runtime/debian.changelog
data/obs-packaging/cc-oci-runtime/update_runtime.sh

Tis commit adds improvements to the OBS automation tooling for cc-oci-runtime, and the updated changelog sent to the OBS builds.

build: Update cc-oci-runtime obs builds with master

---

configure.ac

2.1.9 changes:
- Fixed CentOS build issues
- Removed autoarchive-conf dependency for newest version
- Prevent race condition in cc-proxy.
4591c57 proxy: Avoid shadowing type "header" with variable "header"
161aa5c configure: Remove AX_VALGRIND_DFLT references
faa84b1 tests: updated user.bats to check group id with a regex
7ff8e07 CI: Update Coverity Scan token used by TravisCI.
61e9dbc Revert "versions: Specifies a version of autoconf-archive"
c2c1853 docs: Edit the updated instructions to install Docker.
4fdc46f docs: Update instructions to install latest Docker
78689d1 Prevent race condition with the per-client ID
3615fd0 shim: Fix debug messgage
aa3d951 shim: Compare errno with EINTR instead of return value of write
043bb40 shim: Make the shim exit in case of erroneous stream lengths …

release: 2.1.9

---

tests/metrics/network/lib/network-test-common.bash
tests/metrics/network/network-latency.sh
tests/metrics/network/network-metrics-cpu-consumption.sh.in
tests/metrics/network/network-metrics-iperf3.sh
tests/metrics/network/network-metrics-memory-pss.sh.in
tests/metrics/network/network-metrics-nuttcp.sh
tests/metrics/network/network-metrics.sh

Add common file of functions that are shared among networking
tests that are using iperf and nuttcp. These functions include
setup the environment, start a server, start a client and
clean up the environment.

Tests: Common file for networking tests

---

proxy/proxy.go

The previous pull request #897 is incomplete. The potential for a race
condition still exists because there is a gap between when the client ID
is incremented and when the client ID is later assigned. Copying the
return value from the atomic intermenting operation as a local variable
in the function to close the gap.

Copy client ID locally to prevent race condition

---

Makefile.am
tests/metrics/network/network-metrics-memory-rss-1g.sh.in

Resident Set Size (RSS) memory while running a nuttcp 1 Gb transfer rate.
The RSS measurement is taken by using smem.
Fixes #925.

Metrics: Measure RSS memory for 1Gb transfer

---

data/obs-packaging/cc-oci-runtime/debian.changelog
data/obs-packaging/cc-oci-runtime/update_runtime.sh

Added OBS_RUNTIME_REPO as an option to set different OBS repositories to
allow us to push to user's OBS clone's, staging, prod.
Updated debian.changelog with release 2.1.9

build: Add extra variable for OBS builds

---

configure.ac

release: version 2.1.10
- Removed old dockerfiles, clear containers dockerfiles live in
github.com/clearcontainers/dockerfiles
- Installation Documentation updated for Centos 7
- Prevented race condition in proxy client ID assignment
- Added metrics to measure RSS memory for 1Gb transfer
- OBS packaging scripts support  set user's OBS HOME
Short log:
a923745 Changes to installation documentation for Centos
06ea638 build: Add extra variable for OBS builds
41a405c #927 from GabyCT/topic/rssmemory
87ca55a Metrics: Measure RSS memory for 1Gb transfer
197e8d4 Copy client ID locally to prevent race condition
a923745 Changes to installation documentation for Centos
3c54712 Tests: Common file for networking tests
ac90d7d remove unused files
06ea638 build: Add extra variable for OBS builds
ac90d7d …

Release 2.1.10

---

tests/metrics/network/README.md

Correct the typo in the network metrics build command, and clarify
how the tests can be run by hand after pre-processing.
Fixes: #944

Docs: metrics: network: Clarify pre-process and running

---

data/obs-packaging/cc-oci-runtime/debian.changelog
data/obs-packaging/clear-containers-image/update_image.sh
data/obs-packaging/linux-container/update_kernel.sh

build: Fix OBS variables in package helper scripts
There is a bug on the repo variables to use. 
``OBS_CC_IMAGE_REPO``
``OBS_KERNEL_REPO``
Update changelog to package cc-oci-runtime in OBS

Fix OBS variables

---

Makefile.am
proxy/api/protocol.go
proxy/api/protocol_test.go

We can check better the header we receive from clients. This time, make
sure the payload length is within reasonable limits and that the flags
are 0 (we don't have any at the moment).

proxy/protocol: Add checks on header length and flags

---

.ci/ci-pre-checks.sh

Lets ignore checkcommits errors by know. This will allow
to know missing cases.

CI: Ignore checkcommits

---

configure.ac

- kernel: Update kernel  and image versions
- pod: Support new CRI-O namespaces
- CI: Ignore checkcommits
- CI: Perform basic checks on PR commits.
- proxy/protocol: Add checks on header length and flags
- Metrics: PSS for a transfer rate of 1Gb
- Fix OBS variables
- Docs: metrics: network: Clarify pre-process and running
cc9e174 obs: fix patch automation updates for kernel.
7d538ba (origin/update-kernel, update-kernel) kernel: Update kernel version
da039db pod_test: Add a pod namespace unit test
7799fdc pod: Support new CRI-O namespaces
3cfe847 (origin/ignore-checkcommits) CI: Ignore checkcommits
cc7ece4 CI: Perform basic checks on PR commits.
e97073b proxy/protocol: Add checks on header length and flags
1589937 proxy: Add api to the list of packages to test
128d629 Metrics: PSS for a …

Release: 2.1.11

---

documentation/Installing-Clear-Containers-on-Fedora.md

Provide a way to download the clear containers package using
/etc/os-release
Add Fedora 26 to the list of Fedora Versions that can run Clear
Containers 2.1.

docs: Update Clear Containers 2.1 Fedora docs

---

data/obs-packaging/cc-oci-runtime/debian.changelog
data/obs-packaging/clear-containers-image/wd/debian/changelog
data/obs-packaging/linux-container/wd/debian/changelog

This patch updates the changelog generated after build 2.1.11
in OBS:
http://download.opensuse.org/repositories/home:clearlinux:preview:clear-containers-2.1/Fedora_25/
Fixes: #974

build: obs: Update post release changelog

---

tests/integration/docker/dns.bats
tests/integration/docker/mtu.bats
tests/integration/docker/swarm.bats
tests/lib/test-common.bash.in

This PR uses the function the new added check_swarm_replicas in swarm tests.
It removes the infinite loop that potentially can hang the test.
The function check_swarm_replicas: Will wait until all the replicas
from a docker swarm service are ready. It also uses a timeout
if after the timeout is finished the function will fail.
Fixes: #938

Fix docker swarm tests in docker 17

---

configure.ac

- kernel: update to version 4.9.32                                  
- build: obs: Update obs changelog for clear-containers-image       
- misc: Remove NEWS file.                                           
- artifacts: Update kernel and image for clear-containers           
- Fix docker swarm tests in docker 17                               
- build: obs: Update post release changelog                         
- docs: Update Clear Containers 2.1 Fedora docs                     
- build: Makefile: Add generate-files rule                          
c0200a3 kernel: update to version 4.9.32                            
b395ad0 build: obs: Update obs changelog for clear-containers-image 
d09d4fc misc: Remove NEWS file.                                     
71d4ec2 artifacts: Update kernel and …

Release 2.1.12

---

Makefile.am
README.rst
configure.ac
installation/install_clear_image.sh
installation/install_clear_kernel.sh

If a user pulls down cc-oci-runtime and does a make install, Clear
Containers will not work. It is assumed that binary artifacts are
already installed.
This adds `make artifacts` as an option to download and install `clear-containers-kernel` and `clear-containers-image.`
Fixes: #912

build: Adds option to install kernel and image

---

Makefile.am
tests/lib/send_results.sh.in
tests/lib/test-common.bash.in
tests/metrics/README.md
tests/metrics/density/docker_memory_usage.sh.in

The metrics report through more than one method at present (csv files, stdout). Add a more formal and flexible method for reporting metrics results so we can then migrate all the metrics over to 'one true method'.
Fixes: #954

tests: metrics: formalise the metrics reporting methods

---

proxy/proxy.go

This verify the socket path length according to http://man7.org/linux/man-pages/man7/unix.7.html.
The proxy fails correctly when the socket path is too long, but the message is too generic: `bind: invalid argument`.
Fixes #995

proxy: Better error message for too long socket path

---

Makefile.am
data/cc-sriovdownscript.sh
src/command.c
src/hypervisor.c
src/hypervisor.h
src/networking.c
src/networking.h
src/oci.c
src/oci.h
src/process.c
src/process.h
src/state.c

Testing and debug of an issue with the CNM plugin for SRIO-V is still underway, but since this adds a substantial amount of code, I wanted to be more proactive on posting it for feedback.
This could be squashed later, but for now I wanted to preserve the history so you can see what was being taken from 1.x COR versus what needed to be cleaned up.  I also wanted to make sure original author is credited.

RFC: srio-v enabling on 2.1.11

---

configure.ac
tests/functional/run-functional-tests.sh.in

This patch adds a warnings at configuration time, it will
show a warning message when either clear containers kernel
or image are not found.
It also check if a kernel or image was installed by clear containers
packages. If they are installed it will use them as default paths. This
is useful for people that want to use `cc-oci-runtime` compiled from
source but had a previous installation from packages.
Fixes: #769

configure: Add warning when kernel or image is not found

---

data/cc-oci-runtime.sh.in

We can assume that most of the time using
cc-oci-runtime.sh means we're looking for some debug information.

cc-oci-runtime.sh: Enable debug by default

---

data/obs-packaging/linux-container/config

Kernel config has been updated to enable xfs file system support.
This is required for mounting block devices that have xfs file
system type.

obs: Update packaging to include kernel config changes for xfs

---

configure.ac

- Devicemapper storage: Added support to use device mapper volumes  as storage devices instead mount a shared rootfs with 9pfs.
- This allow to use a compatible posix file system and fix issues like #669
- version: Update container image to 16020
- obs: Update packaging to include kernel config changes for xfs
- cc-oci-runtime.sh: Enable debug by default
- configure: Add warning when kernel or image is not found
- proxy: Better error message for too long socket path
- tests: metrics: formalise the metrics reporting methods
- build: Add option to install kernel and image
271223a tests: Skip docker cp integration test for devicemapper storage
9b91166 tests: Fix functional tests to include workload directory
66cbd66 tests: Fix state tests and add check for workload_dir.
b8ffdb1 tests: Fix …

release: 2.2.0

---

.ci/ci-pre-checks.sh

checkcommits has been running successfuly for a while now, so disallow
it failing in a CI environment.
Additionally, only run it in a TravisCI environment since it cannot
currently work under SemaphoreCI (due to its restrictive environment).
Fixes #967 (but actually fixed by https://github.com/clearcontainers/tests/pull/64).

CI: Enforce checkcommits.

---

proxy/cc-proxy.service.in

We were hitting this limit before hitting memory limits in our density
test. Remove it. Linux still has a global limit that will apply, of
course.
Fixes: https://github.com/01org/cc-oci-runtime/issues/1008

proxy: Lift the numbers of opened file descriptors limit

---

tests/integration/docker/dns.bats
tests/integration/docker/swarm.bats
tests/lib/test-common.bash.in

Newest nginx docker image (1.13.1) does not contain `ip`
command by default, which we use in our swarm tests. This
commit specifies to use 1.13.0 which contains `ip`.

tests: Use nginx:1.13.0 for swarm tests

---

data/cc-agent.service

In case we are using a block device for storage,
perform sync so that cached files are written to storage
before VM is shutdown.

storage: Perform sync operation before vm is shutdown

---

shim/shim.c

Include config.h to include the package version.
Add command line option to show version information.
Fixes #981

version: Add command line option to show version information

---

configure.ac

- versions: update kernel to linux-container-4.9.34-75
- shim: Add command line option to show version information
- storage: Perform sync operation before vm is shutdown
- tests: Use nginx:1.13.0 for swarm tests
- proxy: Lift the numbers of opened file descriptors limit
- CI: Enforce checkcommits.
- Fix unnecessary bash-isms in installation script
3eeda89 versions: update kernel to linux-container-4.9.34-75
4e8f155 version: Add command line option to show version information
21b874a storage: Perform sync operation before vm is shutdown
191e9f8 tests: Use nginx:1.13.0 for swarm tests
2f22de2 proxy: Lift the numbers of opened file descriptors limit
55eba02 CI: Enforce checkcommits.
6566262 Fix unnecessary bash-isms in installation script
Clear Containers 2.2.1 is compatible with Docker …

release: 2.2.1

---

installation/curl-autoconf-archive.sh
installation/rhel-setup.sh

Under some circumstances it is needed to 'hand install' the m4
scripts. This was done in the rhel install script, but sometimes
it is really useful to be able to do that by hand, so extract the
relevant commands into their own script (to allow hand running),
and get the rhel script to invoke that new script at the appropriate
time.
Fixes: #875

install: Extract autoconf-archive install to separate script

---

tests/lib/test-common.bash.in

Use the docker hub image gabyct/nginx for our swarm tests.
Fixes #1027

Tests: Change nginx image for swarm tests

---

src/oci.c
tests/functional/kill.bats

This PR add validation in `delete` command, delete must fail if the container is not `stopped`.
Fixes #1018

delete: Fail if try to delete a non-stopped container.

---

tests/integration/docker/Dockerfiles/Dockerfile.nginx
tests/integration/docker/Dockerfiles/README.md

This dockerfile will build an image for nginx for the swarm tests
that we currently have in clear containers.
Fixes #1014

Tests: Dockerfile for Nginx for swarm tests

---

configure.ac

- Tests: Dockerfile for Nginx for swarm tests                                                                                           
- delete: Fail if try to delete a non-stopped container.            
91aacdf Tests: Dockerfile for Nginx for swarm tests                                                                                     
5121969 delete: allow destroy_pod fail if vm die
29f8aa2 tests: functional: check delete fails without kill                                                                              
a51537c delete: Delete container only if state is STOPPED           
Clear Containers 2.2.3 is compatible with Docker v17.05.0-ce                                                                            
Clear Containers 2.2.3 support the OCI Runtime Specification …

Release 2.2.3

---

documentation/Quickstart-Clear-Containers-in-a-Ubuntu-VM.md

We've changed a bit how ciao-down creates new VMs so it's not tied to
ciao as much as before. See:
https://github.com/01org/ciao/pull/1362
Update the documentation to follow that change.

documentation: ciao-down prepare is now ciao-down create

---

versions.txt

This version includes hyperstart fixes:
exec: Return ERROR if the executed process could not start
Fixes: #1047

versions: Update image to version 16670

---

configure.ac

- versions: Update image to version 16670                  
- OBS: add dependencies' versions                          
- documentation: ciao-down prepare is now ciao-down create 
cbdfd1d versions: Update image to version 16670                                  
2c13fb1 OBS: add dependencies' versions                    
68d00dc documentation: Add the -u flag when go getting ciao-down                                                       
0c9d6bb documentation: ciao-down prepare is now ciao-down create                                                       
Clear Containers 2.2.4 is compatible with Docker v17.05.0-ce                                                           
Clear Containers 2.2.4 support the OCI Runtime Specification [1.0.0-rc5][ocispec] …

Release 2.2.4

---

documentation/Installing-Clear-Containers-on-Ubuntu.md

The URL in the `curl` command for fetching the Release key is missing
the directory slashes.  This commit corrects this.
Fixes: #1051
Signed-off-by: dan pittman <danielscottt@gmail.com>

Add missing slashes in key URL
